// Generated by @jarenjs/emit from packages/mas/schemas.
// Do not edit: regenerate instead.

/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type RegistrySha256 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type RegistryName = string;

export interface MasRegistryRolesItem {
  id: RegistryName;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  title: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  instructions: string;
  instructionsRevision: RegistrySha256;
  capabilities: Array<RegistryName>;
}


export interface MasRegistryHandlersItem {
  id: RegistryName;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  title: string;
  effect: "pure" | "read" | "effectful";
  /**
   * `honored` — the bound host handler accepts and honors an out-of-band idempotency key; required before an effectful handler may bind.
   */
  idempotency: "not-required" | "honored";
}


export interface MasRegistryToolsItem {
  id: RegistryName;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  title: string;
  effect: "pure" | "read" | "effectful";
  input: { [key: string]: unknown; } | boolean;
  inputRevision: RegistrySha256;
}


export interface MasRegistryMessageAdaptersItem {
  id: RegistryName;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  version: string;
}


export interface MasRegistryContextAdaptersItem {
  id: RegistryName;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  title: string;
  capabilities: Array<RegistryName>;
}


export interface MasRegistryTemplatesItem {
  id: RegistryName;
  versionId: RegistrySha256;
  /**
   * The embedded MasTemplateVersion document, validated against its own schema by the snapshot constructor.
   */
  template: { [key: string]: unknown; };
}


export interface MasRegistrySubgraphsItem {
  id: RegistryName;
  versionId: RegistrySha256;
  /**
   * The embedded MasWorkflowVersion document, validated against the workflow schema by the snapshot constructor; its versionId must recompute.
   */
  workflow: { [key: string]: unknown; };
}


/**
 * The validated capability snapshot a workflow pins by revision: role identities with content-addressed instructions, named task handler contracts, schema-checked tool declarations, message and context adapter identities, immutable template versions and embedded subgraph workflow versions. Entries are data descriptions only — a function, credential, URL or mutable reference has no representable member; host registries bind functions to these ids only after the snapshot validates. The snapshot revision is the canonical SHA-256 of this whole document.
 * Schema constraints this type cannot express: $query={"$and":[{"$eq":[{"$count":"$.roles[*].id"},{"$count":{"$distinct":"$.roles[*].id"}}]},{"$eq":[{"$count":"$.handlers[*].id"},{"$count":{"$distinct":"$.handlers[*].id"}}]},{"$eq":[{"$count":"$.tools[*].id"},{"$count":{"$distinct":"$.tools[*].id"}}]},{"$eq":[{"$count":"$.messageAdapters[*].id"},{"$count":{"$distinct":"$.messageAdapters[*].id"}}]},{"$eq":[{"$count":"$.contextAdapters[*].id"},{"$count":{"$distinct":"$.contextAdapters[*].id"}}]},{"$eq":[{"$count":"$.templates[*].id"},{"$count":{"$distinct":"$.templates[*].id"}}]},{"$eq":[{"$count":"$.subgraphs[*].id"},{"$count":{"$distinct":"$.subgraphs[*].id"}}]}]}
 */
export interface MasRegistry {
  $masRegistry: "0.1";
  registryId: RegistryName;
  roles: Array<MasRegistryRolesItem>;
  handlers: Array<MasRegistryHandlersItem>;
  tools: Array<MasRegistryToolsItem>;
  messageAdapters: Array<MasRegistryMessageAdaptersItem>;
  contextAdapters: Array<MasRegistryContextAdaptersItem>;
  templates: Array<MasRegistryTemplatesItem>;
  subgraphs: Array<MasRegistrySubgraphsItem>;
}


/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type RuntimeSha256 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type RuntimeName = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type RecordId = string;

/**
 * An injected-clock reading, ISO-8601 shaped. Deterministic ticks under conformance; never part of a canonical identity.
 * Schema constraints this type cannot express: minLength=1
 */
export type Tick = string;

/**
 * The hierarchical invocation address `<region>/<branch>/<iteration>/<node>` segments joined by `/`; iterations are 1-based decimals.
 * Schema constraints this type cannot express: minLength=1
 */
export type InvocationPath = string;

export type RunStatus = "queued" | "running" | "waiting_for_input" | "resume_pending" | "completed" | "failed" | "cancelled";

export type AttemptStatus = "running" | "completed" | "failed" | "aborted" | "uncertain";

export interface RuntimeErrorCauseOneOf2 {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  code: string;
  docPath: string;
  message: string;
}


export interface RuntimeError {
  /**
   * Schema constraints this type cannot express: pattern="^(TMAS[12][0-9]{3}|JF[0-9]{4}|JQ[0-9]{4}|JD[0-9]{4})$"
   */
  code: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: string;
  cause: null | RuntimeErrorCauseOneOf2;
}


export interface BudgetSpend {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  turns: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  tokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  ms: number;
}


export interface UsageCounts {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  toolCalls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  contextReads: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  promptTokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  completionTokens: number;
}


/**
 * A bounded, redaction-safe view of a larger value. `state` says exactly why bytes may be absent; `text` is the retained bounded rendering.
 */
export interface BoundedView {
  state: "retained" | "redacted" | "truncated" | "expired" | "not-configured" | "not-run";
  text: null | string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  size: number;
  artifact: null | RecordId;
}


export interface ToolStep {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  name: string;
  arguments: BoundedView;
  result: BoundedView;
  state: "ok" | "invalid-input" | "handler-error" | "aborted" | "uncertain";
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type ContextReadAddressesItem = string;

export interface ContextRead {
  adapter: RuntimeName;
  outcome: "ok" | "unavailable" | "failed";
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  units: number;
  addresses: Array<ContextReadAddressesItem>;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  chars: number;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type MasRunClaimOwnerOneOf2 = string;

/**
 * The worker claim epoch: bumped on every segment claim/reclaim, never by ordinary record writes. A semantic commit carrying a stale claim seq refuses TMAS2005 — a zombie worker whose lease expired cannot write a completion.
 */
export interface MasRunClaim {
  owner: null | MasRunClaimOwnerOneOf2;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  seq: number;
}


export interface RunFailure {
  node: null | InvocationPath;
  error: RuntimeError;
}


export interface MasRun {
  id: RecordId;
  workflowId: RuntimeName;
  workflowVersionId: RuntimeSha256;
  registryRevision: RuntimeSha256;
  executableRevision: RuntimeSha256;
  configRegistryRevision: null | RuntimeSha256;
  profile: RuntimeName;
  status: RunStatus;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  revision: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  segment: number;
  /**
   * The worker claim epoch: bumped on every segment claim/reclaim, never by ordinary record writes. A semantic commit carrying a stale claim seq refuses TMAS2005 — a zombie worker whose lease expired cannot write a completion.
   */
  claim: MasRunClaim;
  /**
   * The per-run trace sequence authority: record ids derive from it transactionally, so the trace order is committed state, never a process-local counter.
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  traceSeq: number;
  jobId: null | RecordId;
  input: unknown;
  output: unknown;
  failure: null | RunFailure;
  /**
   * Persisted suite FSM snapshots and host context per control descriptor id — the whole durable control state of the run.
   */
  fsm: { [key: string]: unknown; };
  budget: { limits: { [key: string]: unknown; }; spent: BudgetSpend; };
  createdAt: Tick;
  updatedAt: Tick;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type MasNodeAttemptStopReasonOneOf2 = string;

export interface MasNodeAttempt {
  id: RecordId;
  runId: RecordId;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  seq: number;
  path: InvocationPath;
  invocationId: RuntimeName;
  kind: "agent" | "task" | "graph" | "loop" | "switch" | "interaction";
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  attempt: number;
  status: AttemptStatus;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  idempotencyKey: string;
  output: unknown;
  error: null | RuntimeError;
  usage: UsageCounts;
  spend: BudgetSpend;
  stopReason: null | MasNodeAttemptStopReasonOneOf2;
  transcript: BoundedView;
  toolSteps: Array<ToolStep>;
  contextReads: Array<ContextRead>;
  restored: boolean;
  startedAt: Tick;
  finishedAt: null | Tick;
}


export interface MessageEnd {
  path: InvocationPath;
  port: RuntimeName;
}


export interface MasMessage {
  id: RecordId;
  runId: RecordId;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  seq: number;
  edgeId: RuntimeName;
  from: MessageEnd;
  to: MessageEnd;
  adapter: RuntimeName;
  aggregation: "one" | "ordered-list" | "named-object";
  /**
   * The edge-document-order position among the target port's inbound edges — the aggregation order, independent of completion timing.
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  index: number;
  payload: unknown;
  payloadState: "retained" | "redacted" | "truncated" | "expired";
  artifact: null | RecordId;
  at: Tick;
}


/**
 * Schema constraints this type cannot express: pattern="^/"
 */
export type MasStateRevisionProvenanceMembersItem = string;

export interface MasStateRevision {
  id: RecordId;
  runId: RecordId;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  seq: number;
  /**
   * The state owner: '' for the workflow root, or the graph invocation path for an isolated child namespace.
   */
  namespace: string;
  parent: null | RecordId;
  value: unknown;
  provenance: { path: InvocationPath; members: Array<MasStateRevisionProvenanceMembersItem>; };
  at: Tick;
}


export interface MasInteractionExpiryOneOf2 {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  afterMs: number;
  deadline: Tick;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type MasInteractionResponseKeyOneOf2 = string;

/**
 * Schema constraints this type cannot express: type="integer", minimum=1
 */
export type MasInteractionResumeSegmentOneOf2 = number;

export interface MasInteraction {
  id: RecordId;
  runId: RecordId;
  node: RuntimeName;
  path: InvocationPath;
  status: "waiting" | "responded" | "cancelled" | "expired";
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  revision: number;
  prompt: unknown;
  responseSchema: { [key: string]: unknown; } | boolean;
  expiry: null | MasInteractionExpiryOneOf2;
  response: unknown;
  responseKey: null | MasInteractionResponseKeyOneOf2;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  segment: number;
  resumeSegment: null | MasInteractionResumeSegmentOneOf2;
  requestedAt: Tick;
  resolvedAt: null | Tick;
}


export interface MasTraceArtifact {
  id: RecordId;
  runId: RecordId;
  kind: "transcript" | "tool-arguments" | "tool-result" | "message-payload" | "context-unit" | "normalization";
  state: "retained" | "redacted" | "truncated" | "expired";
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  size: number;
  bytes: null | string;
  at: Tick;
}


/**
 * Store-neutral runtime records: the run, the node attempt, the message, the state revision, the interaction and the bounded trace artifact. Persistence implements collections over exactly these shapes; the runtime constructs them; the conformance instrument reads them. Timestamps come from the injected host clock (deterministic ticks under conformance) and never enter a canonical identity. Credential values have no representable member, and every omitted payload is an explicit state — `retained`, `redacted`, `truncated`, `expired`, `not-configured` or `not-run` — never a silent absence.
 */
export type MasRuntime = MasRun | MasNodeAttempt | MasMessage | MasStateRevision | MasInteraction | MasTraceArtifact;

/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type TemplateSha256 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TemplateName = string;

export interface MasTemplateProvenance {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  author: string;
}


export interface MasTemplateBindingsItem {
  /**
   * Schema constraints this type cannot express: pattern="^/"
   */
  parameterPointer: string;
  /**
   * Schema constraints this type cannot express: pattern="^/"
   */
  targetPointer: string;
  /**
   * What the binding may change: role instructions or profile references, a requested tool subset, a message/context adapter choice, node/workflow caps (never above a parent), or the enablement value of a declared switch branch guard.
   */
  mode: "instructions-revision" | "role" | "profile" | "tools" | "message-adapter" | "context-adapter" | "caps" | "branch-enablement";
}


/**
 * An immutable workflow fragment plus the closed parameter schema and the ordered binding declarations that alone may specialize it. Instantiation validates parameters with the suite validator, applies a compiled RFC 6902 patch whose operations target only declared pointers, validates the result as a normal MasWorkflowVersion, and records template version and parameter revision as provenance. A parameter cannot change a node kind, add a node/edge/tool, target an undeclared pointer, or raise a cap. The template `versionId` is the canonical SHA-256 of the document with `versionId` and `provenance` excluded.
 */
export interface MasTemplate {
  $masTemplate: "0.1";
  templateId: TemplateName;
  versionId: TemplateSha256;
  parentVersionId: null | TemplateSha256;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  title: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  description: string;
  provenance: MasTemplateProvenance;
  /**
   * A complete MasWorkflowVersion document (validated against the workflow schema by the template validator) that instantiation specializes copy-on-write.
   */
  fragment: { [key: string]: unknown; };
  parameters: { schema: { [key: string]: unknown; } | boolean; };
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  bindings: Array<MasTemplateBindingsItem>;
}


/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type Sha256 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type Name = string;

/**
 * An embedded JSON Schema document. The semantic validator compiles it; a schema that does not compile refuses.
 */
export type JsonSchema = { [key: string]: unknown; } | boolean;

export interface SchemaCarrier {
  schema: JsonSchema;
}


/**
 * A Jaren JSON Query document — an operator object, a `$`-rooted path string, or a literal; never null, so a nullable member's oneOf stays decidable. Compilability is a semantic gate.
 * Schema constraints this type cannot express: not={"type":"null"}
 */
export type QueryDocument = unknown;

export interface PortRef {
  node: Name;
  port: Name;
}


export interface Ports {
  /**
   * Schema constraints this type cannot express: minProperties=1, propertyNames={"pattern":"^[a-z][a-z0-9-]*$"}
   */
  ports: { [key: string]: { schema: JsonSchema; }; };
}


export interface StatePullItem {
  /**
   * Schema constraints this type cannot express: pattern="^/"
   */
  member: string;
  as: Name;
}


export type StatePull = Array<StatePullItem>;

export interface StatePushItem {
  from: Name;
  /**
   * Schema constraints this type cannot express: pattern="^/"
   */
  member: string;
}


export type StatePush = Array<StatePushItem>;

/**
 * Schema constraints this type cannot express: minProperties=1
 */
export interface NodeLimitsOneOf2 {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls?: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  tokens?: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  ms?: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  toolRounds?: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  contextChars?: number;
}


export type NodeLimits = null | NodeLimitsOneOf2;

export interface WorkflowLimits {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  tokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  ms: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  toolRounds: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  fanOut: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  concurrency: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  iterations: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  contextChars: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  traceBytes: number;
}


export interface MessageEdge {
  id: Name;
  from: PortRef;
  to: PortRef;
  adapter: Name;
  select: null | QueryDocument;
  aggregation: "one" | "ordered-list" | "named-object";
}


export interface AgentNode {
  id: Name;
  kind: "agent";
  input: Ports;
  output: Ports;
  statePull: StatePull;
  statePush: StatePush;
  limits: NodeLimits;
  role: Name;
  profile: Name;
  instructionsRevision: Sha256;
  tools: Array<Name>;
  context: Array<Name>;
  messageAdapter: Name;
}


export interface TaskNode {
  id: Name;
  kind: "task";
  input: Ports;
  output: Ports;
  statePull: StatePull;
  statePush: StatePush;
  limits: NodeLimits;
  handler: Name;
  effect: "pure" | "read" | "effectful";
}


export interface GraphNodePullItem {
  /**
   * Schema constraints this type cannot express: pattern="^/"
   */
  parent: string;
  /**
   * Schema constraints this type cannot express: pattern="^/"
   */
  child: string;
}


export interface GraphNodePushItem {
  /**
   * Schema constraints this type cannot express: pattern="^/"
   */
  child: string;
  /**
   * Schema constraints this type cannot express: pattern="^/"
   */
  parent: string;
}


export interface GraphNode {
  id: Name;
  kind: "graph";
  input: Ports;
  output: Ports;
  statePull: StatePull;
  statePush: StatePush;
  limits: NodeLimits;
  subgraph: Name;
  pull: Array<GraphNodePullItem>;
  push: Array<GraphNodePushItem>;
}


export interface LoopNode {
  id: Name;
  kind: "loop";
  input: Ports;
  output: Ports;
  statePull: StatePull;
  statePush: StatePush;
  limits: NodeLimits;
  body: Name;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  init: Array<{ port: Name; to: string; }>;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  feedback: Array<{ from: string; to: string; }>;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  result: Array<{ port: Name; from: string; }>;
  /**
   * The host-owned iteration cap. Positivity is the semantic gate, so an unbounded declaration refuses at its own pointer rather than as a shape error.
   * Schema constraints this type cannot express: type="integer"
   */
  maxIterations: number;
  termination: QueryDocument;
}


export interface SwitchNodeBranchesItem {
  id: Name;
  when: QueryDocument;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  nodes: Array<Name>;
  result: PortRef;
}


export interface SwitchNode {
  id: Name;
  kind: "switch";
  input: Ports;
  output: Ports;
  statePull: StatePull;
  statePush: StatePush;
  limits: NodeLimits;
  mode: "one-of" | "multi-select";
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  branches: Array<SwitchNodeBranchesItem>;
  default: null | Name;
}


export interface InteractionNodeExpiryOneOf2 {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  afterMs: number;
}


export interface InteractionNode {
  id: Name;
  kind: "interaction";
  input: Ports;
  output: Ports;
  statePull: StatePull;
  statePush: StatePush;
  limits: NodeLimits;
  prompt: SchemaCarrier;
  response: SchemaCarrier;
  expiry: null | InteractionNodeExpiryOneOf2;
}


export type Invocation = AgentNode | TaskNode | GraphNode | LoopNode | SwitchNode | InteractionNode;

export interface MasWorkflowProvenance {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  author: string;
}


/**
 * The immutable, content-addressed intermediate representation every authoring path emits and the only shape the runtime executes. A version carries its stable workflow id, its canonical `versionId` (the SHA-256 of the document with `versionId`, `provenance` and `compile` excluded, so authorship and source provenance can never move a version), closed input/output/state schemas, named entry/exit ports, the closed six-kind invocation union, control dependencies, ordered typed message edges, workflow/node caps, pinned registry and CONFIG references and compile metadata. Secrets, clocks and observed results have no representable member. Unknown members refuse at every object.
 * Schema constraints this type cannot express: $query={"$and":[{"$eq":[{"$count":"$.nodes[*].id"},{"$count":{"$distinct":"$.nodes[*].id"}}]},{"$eq":[{"$count":"$.messages[*].id"},{"$count":{"$distinct":"$.messages[*].id"}}]},{"$every":{"n":"$.nodes[?(@.kind=='switch')]"},"$satisfies":{"$eq":[{"$count":"$n.branches[*].id"},{"$count":{"$distinct":"$n.branches[*].id"}}]}}]}
 */
export interface MasWorkflow {
  $mas: "0.1";
  workflowId: Name;
  versionId: Sha256;
  parentVersionId: null | Sha256;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  title: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  description: string;
  provenance: MasWorkflowProvenance;
  input: SchemaCarrier;
  output: SchemaCarrier;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  entry: Array<{ port: Name; to: PortRef; }>;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  exit: Array<{ port: Name; from: PortRef; }>;
  state: { schema: JsonSchema; init: unknown; };
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  nodes: Array<Invocation>;
  control: Array<{ from: Name; to: Name; }>;
  messages: Array<MessageEdge>;
  limits: WorkflowLimits;
  /**
   * The pinned MAS registry snapshot revision. `null` is legal only for a subgraph-embedded child, which inherits the enclosing pin.
   */
  registry: { revision: null | Sha256; };
  config: { registryRevision: null | Sha256; profile: Name; };
  compile: { schemaVersion: "0.1"; sourceMode: "declarative" | "imperative"; sourceDesignRevision: null | Sha256; executableRevision: null | Sha256; };
}


