// Generated by @jarenjs/emit from packages/trading/schemas/trading.schema.json.
// Do not edit: regenerate instead.

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type AnalystReportCitationsItem = string;

export interface AnalystReportModel {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  profile: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  identityId: string;
}


export interface TradingSpend {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  toolCalls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  tokens: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  usd: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  retries: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  repairs: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  ms: number;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradingClaimCitationsItem = string;

export interface TradingClaim {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  citations: Array<TradingClaimCitationsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type AnalystReportSignalsItemReasonAnyOf1 = string;

export interface AnalystReportSignalsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  name: string;
  value: number | null;
  reason: AnalystReportSignalsItemReasonAnyOf1 | null;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type AnalystReportGapsItem = string;

export interface TradingDecisionKey {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  sessionId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  stage: string;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
 */
export type TradingRevision = string;

export interface TradingCitation {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  digest: TradingRevision;
}


export interface TradingFindingOutput {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  citations: Array<TradingCitation>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type AnalystReportOutputLimitationsItem = string;

export interface AnalystReportOutput {
  findings: Array<TradingFindingOutput>;
  signal: "bullish" | "bearish" | "neutral";
  /**
   * Schema constraints this type cannot express: minimum=0, maximum=1
   */
  confidence: number;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  horizon: string;
  limitations: Array<AnalystReportOutputLimitationsItem>;
}


export interface AnalystReport {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  role: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  snapshotId: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  citations: Array<AnalystReportCitationsItem>;
  model: AnalystReportModel;
  spend: TradingSpend;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  promptRevision: string;
  claims: Array<TradingClaim>;
  kind: "analyst-report";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  summary: string;
  signals: Array<AnalystReportSignalsItem>;
  gaps: Array<AnalystReportGapsItem>;
  key: TradingDecisionKey;
  analysis?: AnalystReportOutput;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type DebateTurnCitationsItem = string;

export interface DebateTurnModel {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  profile: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  identityId: string;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type DebateTurnPreviousTurnIdsItem = string;

export interface GmplCitation {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  digest: string;
}


export interface GmplClaim {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  citations: Array<GmplCitation>;
}


export interface GmplFinding {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  origin: string;
  disposition: "supported" | "contested" | "rejected-with-reason" | "unresolved";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reason: string;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  citations: Array<GmplCitation>;
  critical?: boolean;
  contradictory?: boolean;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GmplPatternResultOutstandingQuestionsItem = string;

export interface GmplPatternResult {
  answer: string;
  disposition: "completed" | "no-consensus" | "needs-information" | "rejected";
  claims: Array<GmplClaim>;
  findings: Array<GmplFinding>;
  outstandingQuestions?: Array<GmplPatternResultOutstandingQuestionsItem>;
}


export interface DebateTurn {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  role: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  snapshotId: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  citations: Array<DebateTurnCitationsItem>;
  model: DebateTurnModel;
  spend: TradingSpend;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  promptRevision: string;
  claims: Array<TradingClaim>;
  kind: "debate-turn";
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  round: number;
  persona: "bull" | "bear";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  position: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  previousTurnIds: Array<DebateTurnPreviousTurnIdsItem>;
  key: TradingDecisionKey;
  participant?: "position-1" | "position-2" | "rebuttal-1" | "rebuttal-2";
  phase?: "position" | "rebuttal";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  attemptKey?: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  attemptNumber?: number;
  attemptStatus?: "completed" | "failed" | "aborted" | "uncertain";
  result?: GmplPatternResult | null;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type ResearchVerdictCitationsItem = string;

export interface ResearchVerdictModel {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  profile: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  identityId: string;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type ResearchVerdictHistoryIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type ResearchVerdictRecommendationItem = string;

export interface DebateJudge {
  result: GmplPatternResult;
  action: "accept" | "reject" | "continue" | "escalate";
}


export interface TradingResearchJudgment {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10
   */
  round: number;
  action: "accept" | "continue" | "reject" | "escalate";
  judgment: DebateJudge;
}


export interface ResearchVerdict {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  role: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  snapshotId: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  citations: Array<ResearchVerdictCitationsItem>;
  model: ResearchVerdictModel;
  spend: TradingSpend;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  promptRevision: string;
  claims: Array<TradingClaim>;
  kind: "research-verdict";
  disposition: "accept" | "reject" | "no-consensus" | "completed" | "rejected";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  summary: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  historyIds: Array<ResearchVerdictHistoryIdsItem>;
  key: TradingDecisionKey;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  prevailingThesis?: string;
  recommendation?: Array<ResearchVerdictRecommendationItem>;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10
   */
  rounds?: number;
  result?: GmplPatternResult;
  judgments?: Array<TradingResearchJudgment>;
  unresolvedFindings?: Array<GmplFinding>;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradeProposalCitationsItem = string;

export interface TradeProposalModel {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  profile: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  identityId: string;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradingId = string;

export interface TradeProposal {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  role: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  snapshotId: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  citations: Array<TradeProposalCitationsItem>;
  model: TradeProposalModel;
  spend: TradingSpend;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  promptRevision: string;
  claims: Array<TradingClaim>;
  kind: "trade-proposal";
  action: "buy" | "sell" | "hold";
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  quantity?: number;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  timing: "next-open";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  rationale: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  researchVerdictId: string;
  key: TradingDecisionKey;
  /**
   * Schema constraints this type cannot express: maximum=1, exclusiveMinimum=0
   */
  targetWeight?: number;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  horizon: string;
  assumedPortfolioId: TradingId;
  exceedsPosition: boolean;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type RiskTurnCitationsItem = string;

export interface RiskTurnModel {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  profile: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  identityId: string;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type RiskTurnPreviousTurnIdsItem = string;

export interface RiskTurn {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  role: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  snapshotId: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  citations: Array<RiskTurnCitationsItem>;
  model: RiskTurnModel;
  spend: TradingSpend;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  promptRevision: string;
  claims: Array<TradingClaim>;
  kind: "risk-turn";
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  round: number;
  persona: "risky" | "neutral" | "conservative";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  position: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  previousTurnIds: Array<RiskTurnPreviousTurnIdsItem>;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  proposalId: string;
  key: TradingDecisionKey;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type RiskVerdictCitationsItem = string;

export interface RiskVerdictModel {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  profile: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  identityId: string;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type RiskVerdictHistoryIdsItem = string;

export interface RiskVerdict {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  role: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  snapshotId: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  citations: Array<RiskVerdictCitationsItem>;
  model: RiskVerdictModel;
  spend: TradingSpend;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  promptRevision: string;
  claims: Array<TradingClaim>;
  kind: "risk-verdict";
  disposition: "accept" | "reject" | "no-consensus";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  summary: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  historyIds: Array<RiskVerdictHistoryIdsItem>;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  proposalId: string;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  maxQuantity: number;
  key: TradingDecisionKey;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type FundManagerDecisionCitationsItem = string;

export interface FundManagerDecisionModel {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  profile: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  identityId: string;
}


export interface TradingIssueCause {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  code: string;
  path: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: string;
}


export interface TradingIssue {
  code: "TTRD1001" | "TTRD1002" | "TTRD1003" | "TTRD1004" | "TTRD1005" | "TTRD1006" | "TTRD1007" | "TTRD1008" | "TTRD1009";
  path: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: string;
  cause?: TradingIssueCause;
}


export interface FundManagerDecision {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  role: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  snapshotId: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  citations: Array<FundManagerDecisionCitationsItem>;
  model: FundManagerDecisionModel;
  spend: TradingSpend;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  promptRevision: string;
  claims: Array<TradingClaim>;
  kind: "fund-manager-decision";
  action: "approve" | "modify" | "reject" | "hold";
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  quantity: number;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  proposalId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  riskVerdictId: string;
  violations: Array<TradingIssue>;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  rationale: string;
  key: TradingDecisionKey;
}


export type Artifact = AnalystReport | DebateTurn | ResearchVerdict | TradeProposal | RiskTurn | RiskVerdict | FundManagerDecision;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type BacktestResultDayResultIdsItem = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type BacktestResultPortfolioIdsItem = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type BacktestResultFillIdsItem = string;

export interface BacktestResult {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  kind: "backtest-result";
  status: "completed" | "failed" | "incomplete";
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  dayResultIds: Array<BacktestResultDayResultIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  portfolioIds: Array<BacktestResultPortfolioIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  fillIds: Array<BacktestResultFillIdsItem>;
  spend: TradingSpend;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  incompleteDecisions: number;
  errors: Array<TradingIssue>;
}


export interface BarObservation {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  eventAt: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  availableAt: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sourceId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sourceKey: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  revisionId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  contentHash: string;
  kind: "bar";
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  sessionId: string;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  open: number;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  high: number;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  low: number;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  close: number;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  adjustedClose: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  volume: number;
}


/**
 * Schema constraints this type cannot express: exclusiveMinimum=0
 */
export type CorporateActionObservationRatioAnyOf1 = number;

/**
 * Schema constraints this type cannot express: minimum=0
 */
export type CorporateActionObservationCashPerShareAnyOf1 = number;

export interface CorporateActionObservation {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  eventAt: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  availableAt: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sourceId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sourceKey: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  revisionId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  contentHash: string;
  kind: "corporate-action";
  action: "split" | "dividend";
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  sessionId: string;
  ratio: CorporateActionObservationRatioAnyOf1 | null;
  cashPerShare: CorporateActionObservationCashPerShareAnyOf1 | null;
}


export interface Fill {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  kind: "fill";
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  intentId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  decisionId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  sessionId: string;
  side: "buy" | "sell";
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  quantity: number;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  price: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  commission: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  slippage: number;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  notional: number;
  sourceBarId: TradingId;
}


/**
 * Schema constraints this type cannot express: if={"properties":{"decision":{"const":"rejected"}}}, then={"properties":{"finalIntent":{"properties":{"action":{"const":"hold"}}}}}
 */
export type FundManagerOutputPart1 = unknown;

/**
 * Schema constraints this type cannot express: not={"anyOf":[{"required":["quantity"]},{"required":["targetWeight"]}]}
 */
export interface TradingProposedIntentOneOf1 {
  action?: "hold";
  [key: string]: unknown;
}


/**
 * Schema constraints this type cannot express: not={"required":["targetWeight"]}
 */
export interface TradingProposedIntentOneOf2OneOf1 {
  quantity: unknown;
  [key: string]: unknown;
}


/**
 * Schema constraints this type cannot express: not={"required":["quantity"]}
 */
export interface TradingProposedIntentOneOf2OneOf2 {
  targetWeight: unknown;
  [key: string]: unknown;
}


export type TradingProposedIntent = (TradingProposedIntentOneOf1 | (TradingProposedIntentOneOf2OneOf1 | TradingProposedIntentOneOf2OneOf2) & { action?: "buy" | "sell"; [key: string]: unknown; }) & { action: "buy" | "sell" | "hold"; quantity?: number; targetWeight?: number; };

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type FundManagerOutputReasonsItem = string;

export type FundManagerOutput = FundManagerOutputPart1 & { decision: "approved" | "modified" | "rejected"; finalIntent: TradingProposedIntent; reasons: Array<FundManagerOutputReasonsItem>; citations: Array<TradingCitation>; inputProposalId: TradingId; inputRiskVerdictId: TradingId; };

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type LedgerEntryFillIdAnyOf1 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type LedgerEntryActionIdAnyOf1 = string;

export interface LedgerEntry {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  kind: "ledger";
  fillId: LedgerEntryFillIdAnyOf1 | null;
  actionId: LedgerEntryActionIdAnyOf1 | null;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  sessionId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  account: string;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  debit: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  credit: number;
  purpose?: "principal" | "commission" | "dividend";
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type MarketSessionPrevAnyOf1 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type MarketSessionNextAnyOf1 = string;

export interface MarketSession {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  kind: "session";
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  key: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  calendar: string;
  /**
   * Schema constraints this type cannot express: format="date"
   */
  date: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  openAt: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  closeAt: string;
  prev: MarketSessionPrevAnyOf1 | null;
  next: MarketSessionNextAnyOf1 | null;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type MarketSnapshotObservationIdsItem = string;

export interface MarketSnapshotRefusedItem {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  reason: "TTRD1003";
}


/**
 * Schema constraints this type cannot express: type="integer", minimum=0
 */
export type MarketSnapshotStalenessAnyOf1 = number;

export interface MarketSnapshot {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  kind: "snapshot";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  sessionId: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  cutoffAt: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  observationIds: Array<MarketSnapshotObservationIdsItem>;
  refused: Array<MarketSnapshotRefusedItem>;
  providerErrors: Array<TradingIssue>;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  portfolioId: string;
  staleness: MarketSnapshotStalenessAnyOf1 | null;
}


/**
 * Schema constraints this type cannot express: minimum=-1, maximum=1
 */
export type ReleaseObservationProviderSentimentAnyOf1 = number;

export interface ReleaseObservation {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  eventAt: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  availableAt: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sourceId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sourceKey: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  revisionId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  contentHash: string;
  kind: "fundamental" | "news" | "social" | "insider" | "profile";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  providerSentiment: ReleaseObservationProviderSentimentAnyOf1 | null;
  modelInterpretation: null;
}


export type Observation = BarObservation | ReleaseObservation | CorporateActionObservation;

/**
 * Schema constraints this type cannot express: exclusiveMinimum=0
 */
export type OrderIntentLimitPriceAnyOf1 = number;

/**
 * Schema constraints this type cannot express: exclusiveMinimum=0
 */
export type OrderIntentStopPriceAnyOf1 = number;

export interface OrderIntent {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  kind: "order";
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  decisionId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  decisionSessionId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  fillSessionId: string;
  orderKind: "market" | "limit" | "stop";
  side: "buy" | "sell";
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  quantity: number;
  limitPrice: OrderIntentLimitPriceAnyOf1 | null;
  stopPrice: OrderIntentStopPriceAnyOf1 | null;
}


export interface PortfolioPosition {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  quantity: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  costBasis: number;
  cashFlow: number;
  realizedPnl: number;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type PortfolioSnapshotParentIdAnyOf1 = string;

export interface PortfolioSnapshotMarksItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  price: number;
}


export interface PortfolioSnapshotConcentrationItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  fraction: number;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type PortfolioSnapshotAsOfSessionIdAnyOf1 = string;

export interface PortfolioSnapshot {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  kind: "portfolio";
  parentId: PortfolioSnapshotParentIdAnyOf1 | null;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  sequence: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  cash: number;
  positions: Array<PortfolioPosition>;
  marks: Array<PortfolioSnapshotMarksItem>;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  equity: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  grossExposure: number;
  netExposure: number;
  concentration: Array<PortfolioSnapshotConcentrationItem>;
  realizedPnl: number;
  unrealizedPnl: number;
  asOfSessionId: PortfolioSnapshotAsOfSessionIdAnyOf1 | null;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type RiskPolicyInstrumentsItem = string;

export interface RiskPolicy {
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  grossExposure: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  netExposure: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  singleName: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  cashFloor: number;
  /**
   * Schema constraints this type cannot express: minimum=0, maximum=1
   */
  maxParticipation: number;
  /**
   * Schema constraints this type cannot express: minimum=0, maximum=1
   */
  lossLimit: number;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  instruments: Array<RiskPolicyInstrumentsItem>;
  orderKinds: ["market"];
}


export interface RiskTurnOutputClaimsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  citations: Array<TradingCitation>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type RiskTurnOutputRecommendationsItem = string;

export interface RiskTurnOutput {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  position: string;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  claims: Array<RiskTurnOutputClaimsItem>;
  recommendations: Array<RiskTurnOutputRecommendationsItem>;
}


export interface RiskVerdictOutputAcceptedClaimsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reason: string;
}


export interface RiskVerdictOutputRejectedClaimsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reason: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type RiskVerdictOutputRecommendationsItem = string;

export interface RiskVerdictOutput {
  action: "adjust" | "hold" | "reject" | "continue";
  adjustedIntent: TradingProposedIntent;
  acceptedClaims: Array<RiskVerdictOutputAcceptedClaimsItem>;
  rejectedClaims: Array<RiskVerdictOutputRejectedClaimsItem>;
  findings: Array<TradingFindingOutput>;
  recommendations: Array<RiskVerdictOutputRecommendationsItem>;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  summary: string;
}


/**
 * Schema constraints this type cannot express: not={"anyOf":[{"required":["quantity"]},{"required":["targetWeight"]}]}
 */
export interface TradeProposalOutputOneOf1 {
  action?: "hold";
  [key: string]: unknown;
}


/**
 * Schema constraints this type cannot express: not={"required":["targetWeight"]}
 */
export interface TradeProposalOutputOneOf2OneOf1 {
  quantity: unknown;
  [key: string]: unknown;
}


/**
 * Schema constraints this type cannot express: not={"required":["quantity"]}
 */
export interface TradeProposalOutputOneOf2OneOf2 {
  targetWeight: unknown;
  [key: string]: unknown;
}


export type TradeProposalOutput = (TradeProposalOutputOneOf1 | (TradeProposalOutputOneOf2OneOf1 | TradeProposalOutputOneOf2OneOf2) & { action?: "buy" | "sell"; [key: string]: unknown; }) & { action: "buy" | "sell" | "hold"; quantity?: number; targetWeight?: number; timing: "next-open"; horizon: string; rationale: string; citations: Array<TradingCitation>; assumedPortfolioId: TradingId; };

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type TradingRunManifestAssetsItem = string;

export interface TradingRunManifestSessionRange {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  first: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  last: string;
}


export interface TradingRunManifestProviderSnapshotsItem {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  provider: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  licence: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type TradingRunManifestRolesByProfileAdditional = string;

export interface TradingRunManifestToolManifestItem {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
}


export interface TradingRunManifestRounds {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10
   */
  research: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10
   */
  risk: number;
}


export interface TradingLimits {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  tokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  ms: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  toolRounds: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  fanOut: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  concurrency: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  iterations: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  contextChars: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  traceBytes: number;
}


export interface TradingSignalParametersMacd {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000
   */
  fast: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000
   */
  slow: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000
   */
  signal: number;
}


export interface TradingSignalParametersKdjRsi {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000
   */
  k: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000
   */
  d: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000
   */
  rsi: number;
  /**
   * Schema constraints this type cannot express: minimum=0, maximum=100
   */
  entryJ: number;
  /**
   * Schema constraints this type cannot express: minimum=0, maximum=100
   */
  exitJ: number;
  /**
   * Schema constraints this type cannot express: minimum=0, maximum=100
   */
  entryRsi: number;
  /**
   * Schema constraints this type cannot express: minimum=0, maximum=100
   */
  exitRsi: number;
}


export interface TradingSignalParametersMeanReversion {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=2, maximum=10000
   */
  window: number;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  deviations: number;
  deviation: "sample";
}


export interface TradingSignalParametersSma {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000
   */
  fast: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000
   */
  slow: number;
}


/**
 * Schema constraints this type cannot express: $query={"$and":[{"$lt":["$.macd.fast","$.macd.slow"]},{"$lt":["$.sma.fast","$.sma.slow"]},{"$lt":["$.kdjRsi.entryJ","$.kdjRsi.exitJ"]},{"$lt":["$.kdjRsi.entryRsi","$.kdjRsi.exitRsi"]}]}
 */
export interface TradingSignalParameters {
  price: "causal-adjusted-ohlc";
  macd: TradingSignalParametersMacd;
  kdjRsi: TradingSignalParametersKdjRsi;
  meanReversion: TradingSignalParametersMeanReversion;
  sma: TradingSignalParametersSma;
}


export interface TradingExecutionPolicy {
  strategyId: TradingId;
  kind: "signals" | "oracle" | "do-nothing" | "leaky";
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  entryQuantity: number;
}


export interface TradingRunManifest {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  kind: "manifest";
  mode: "fixture" | "replay" | "shadow";
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  assets: Array<TradingRunManifestAssetsItem>;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  calendar: string;
  sessionRange: TradingRunManifestSessionRange;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  timezone: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  currency: string;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  initialCapital: number;
  decisionCutoff: "session-close";
  fill: "next-open";
  shares: "whole" | "fractional";
  shorting: false;
  leverage: false;
  /**
   * Schema constraints this type cannot express: minimum=0, maximum=10000
   */
  commissionBps: number;
  /**
   * Schema constraints this type cannot express: minimum=0, exclusiveMaximum=10000
   */
  slippageBps: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  sessionsPerYear: number;
  riskFree: { kind: "zero-series"; };
  providerSnapshots: Array<TradingRunManifestProviderSnapshotsItem>;
  rolesByProfile: { [key: string]: TradingRunManifestRolesByProfileAdditional; };
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  promptCatalogRevision: string;
  toolManifest: Array<TradingRunManifestToolManifestItem>;
  rounds: TradingRunManifestRounds;
  limits: TradingLimits;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  seed: number;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{40,64}$"
   */
  sourceRevision: string;
  riskPolicy: RiskPolicy;
  signalParameters?: TradingSignalParameters;
  executionPolicy?: TradingExecutionPolicy;
}


export interface TradingActionsInput {
  manifest: TradingRunManifest;
  portfolio: PortfolioSnapshot;
  session: MarketSession;
  actions: Array<CorporateActionObservation>;
}


export interface TradingActionsResult {
  portfolio: PortfolioSnapshot;
  ledgerEntries: Array<LedgerEntry>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  actionIds: Array<TradingId>;
}


/**
 * Schema constraints this type cannot express: format="date-time"
 */
export type TradingInstant = string;

export type TradingAnalystRole = "fundamentals" | "sentiment" | "news" | "technical";

export interface TradingTargetSignal {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  sessionId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  observationId: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  availableAt: string;
  target: "long" | "flat";
}


export interface TradingAnalystProjectionSignalsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  policy: string;
  value: TradingTargetSignal | null;
}


/**
 * Schema constraints this type cannot express: type="integer", minimum=0
 */
export type TradingAnalystProjectionStalenessAnyOf1 = number;

export interface TradingTechnicalIndicatorsParameters {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  adxPeriod: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  cciPeriod: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  volumePeriod: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  kPeriod: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  dPeriod: number;
}


export interface TradingTechnicalIndicators {
  priceBasis: "causal-adjusted-ohlc";
  parameters: TradingTechnicalIndicatorsParameters;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  observations: number;
  windowStartId: TradingId | null;
  windowEndId: TradingId | null;
  availableAt: TradingInstant | null;
  values: { adx: number | null; plusDI: number | null; minusDI: number | null; cci: number | null; vwap: number | null; volumeRatio: number | null; k: number | null; d: number | null; j: number | null; };
}


export interface TradingAnalystProjection {
  snapshotId: TradingId;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  cutoffAt: TradingInstant;
  role: TradingAnalystRole;
  evidence: Array<{ id: TradingId; digest: TradingRevision; observation: Observation; }>;
  signals: Array<TradingAnalystProjectionSignalsItem>;
  staleness: TradingAnalystProjectionStalenessAnyOf1 | null;
  providerErrors: Array<TradingIssue>;
  indicators: TradingTechnicalIndicators | null;
}


export interface TradingVisibleBar {
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  eventAt: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  availableAt: string;
  kind: "bar";
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  sessionId: string;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  open: number;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  high: number;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  low: number;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  close: number;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  adjustedClose: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  volume: number;
}


/**
 * Schema constraints this type cannot express: exclusiveMinimum=0
 */
export type TradingVisibleActionRatioAnyOf1 = number;

/**
 * Schema constraints this type cannot express: minimum=0
 */
export type TradingVisibleActionCashPerShareAnyOf1 = number;

export interface TradingVisibleAction {
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  eventAt: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  availableAt: string;
  kind: "corporate-action";
  action: "split" | "dividend";
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  sessionId: string;
  ratio: TradingVisibleActionRatioAnyOf1 | null;
  cashPerShare: TradingVisibleActionCashPerShareAnyOf1 | null;
}


/**
 * Schema constraints this type cannot express: minimum=-1, maximum=1
 */
export type TradingVisibleReleaseProviderSentimentAnyOf1 = number;

export interface TradingVisibleRelease {
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  eventAt: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  availableAt: string;
  kind: "fundamental" | "news" | "social" | "insider" | "profile";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  providerSentiment: TradingVisibleReleaseProviderSentimentAnyOf1 | null;
  modelInterpretation: null;
}


export interface TradingAnalystViewSignalsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  policy: string;
  value: TradingTargetSignal | null;
}


/**
 * Schema constraints this type cannot express: type="integer", minimum=0
 */
export type TradingAnalystViewStalenessAnyOf1 = number;

export interface TradingAnalystView {
  snapshotId: TradingId;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  cutoffAt: TradingInstant;
  role: TradingAnalystRole;
  evidence: Array<{ id: TradingId; digest: TradingRevision; data: TradingVisibleBar | TradingVisibleAction | TradingVisibleRelease; }>;
  signals: Array<TradingAnalystViewSignalsItem>;
  staleness: TradingAnalystViewStalenessAnyOf1 | null;
  providerErrors: Array<TradingIssue>;
  indicators: TradingTechnicalIndicators | null;
}


export interface TradingProviderFailure {
  outcome: "unavailable" | "failed";
  code: "TTRD1007";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reason: string;
  cause?: TradingIssue;
}


export interface TradingProviderRefusal {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  reason: "TTRD1003";
  issue: TradingIssue;
}


export interface TradingCalendarProviderResultOneOf2 {
  outcome: "ok";
  value: Array<MarketSession>;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  snapshotId: string;
  refused: Array<TradingProviderRefusal>;
}


export type TradingCalendarProviderResult = TradingProviderFailure | TradingCalendarProviderResultOneOf2;

export interface TradingCalendarRange {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  first: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  last: string;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradingDecisionArtifactIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type TradingDecisionReasonAnyOf1 = string;

export interface TradingDecision {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  kind: "decision";
  key: TradingDecisionKey;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  inputRevision: string;
  disposition: "approved" | "hold" | "rejected";
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  artifactIds: Array<TradingDecisionArtifactIdsItem>;
  reason: TradingDecisionReasonAnyOf1 | null;
}


export interface TradingCommit {
  key: TradingDecisionKey;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  expectedPortfolioId: string;
  decision: TradingDecision;
  intent: OrderIntent | null;
  fills: Array<Fill>;
  ledgerEntries: Array<LedgerEntry>;
  portfolio: PortfolioSnapshot;
  mode: "trade" | "settlement" | "valuation";
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  markBarIds: Array<TradingId>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  actionIds: Array<TradingId>;
}


export interface TradingCommitMarker {
  id: TradingId;
  revision: TradingRevision;
  kind: "decision-commit";
  manifestId: TradingId;
  key: TradingDecisionKey;
  commitRevision: TradingRevision;
  expectedPortfolioId: TradingId;
  decisionId: TradingId;
  intentId: TradingId | null;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  fillIds: Array<TradingId>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  ledgerEntryIds: Array<TradingId>;
  portfolioId: TradingId;
  mode: "trade" | "settlement" | "valuation";
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  markBarIds: Array<TradingId>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  actionIds: Array<TradingId>;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  portfolioSequence: number;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type TradingDayResultStopReasonAnyOf1 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradingDayResultArtifactIdsItem = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradingDayResultFillIdsItem = string;

export interface TradingDayResult {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  kind: "day-result";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  sessionId: string;
  status: "completed" | "failed" | "incomplete" | "refused";
  stopReason: TradingDayResultStopReasonAnyOf1 | null;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  artifactIds: Array<TradingDayResultArtifactIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  fillIds: Array<TradingDayResultFillIdsItem>;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  portfolioId: string;
  spend: TradingSpend;
  errors: Array<TradingIssue>;
}


export interface TradingFillInput {
  manifest: TradingRunManifest;
  portfolio: PortfolioSnapshot;
  intent: OrderIntent;
  session: MarketSession;
  bar: BarObservation | null;
}


export interface TradingFillPlan {
  fill: Fill;
  ledgerEntries: Array<LedgerEntry>;
  portfolio: PortfolioSnapshot;
}


export interface TradingFixtureProviderInput {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  eventAt: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  availableAt: string;
  sessions: Array<MarketSession>;
  observations: Array<Observation>;
}


export interface TradingMarkInput {
  manifest: TradingRunManifest;
  portfolio: PortfolioSnapshot;
  session: MarketSession;
  bars: Array<BarObservation>;
}


export interface TradingMarkResult {
  portfolio: PortfolioSnapshot;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  staleMarks: number;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  missingAssets: Array<string>;
}


export interface TradingObservationProviderResultOneOf2 {
  outcome: "ok";
  value: Array<Observation>;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  snapshotId: string;
  refused: Array<TradingProviderRefusal>;
}


export type TradingObservationProviderResult = TradingProviderFailure | TradingObservationProviderResultOneOf2;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradingProviderBindingsCalendarAnyOf1 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradingProviderBindingsMarketAnyOf1 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradingProviderBindingsFundamentalsAnyOf1 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradingProviderBindingsNewsAnyOf1 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradingProviderBindingsSocialAnyOf1 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradingProviderBindingsInsidersAnyOf1 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
 */
export type TradingProviderBindingsProfilesAnyOf1 = string;

export interface TradingProviderBindings {
  calendar: TradingProviderBindingsCalendarAnyOf1 | null;
  market: TradingProviderBindingsMarketAnyOf1 | null;
  fundamentals: TradingProviderBindingsFundamentalsAnyOf1 | null;
  news: TradingProviderBindingsNewsAnyOf1 | null;
  social: TradingProviderBindingsSocialAnyOf1 | null;
  insiders: TradingProviderBindingsInsidersAnyOf1 | null;
  profiles: TradingProviderBindingsProfilesAnyOf1 | null;
}


export type TradingProviderName = "calendar" | "market" | "fundamentals" | "news" | "social" | "insiders" | "profiles";

export interface TradingProviderSnapshot {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  provider: TradingProviderName;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  eventAt: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  availableAt: string;
  sessions: Array<MarketSession>;
  observations: Array<Observation>;
}


export interface TradingReadToolInput {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset?: string;
  cutoffAt?: TradingInstant;
  since?: TradingInstant;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000
   */
  limit?: number;
}


export type TradingRecord = TradingRunManifest | MarketSession | Observation | MarketSnapshot | Artifact | PortfolioSnapshot | TradingDecision | OrderIntent | Fill | LedgerEntry | TradingDayResult | BacktestResult | TradingCommitMarker;

export interface TradingReplayProviderInput {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z][a-z0-9-]*$"
   */
  manifestId: string;
  snapshots: Array<TradingProviderSnapshot>;
  bindings: TradingProviderBindings;
}


export interface TradingRiskInput {
  manifest: TradingRunManifest;
  portfolioAfter: PortfolioSnapshot;
  intent: OrderIntent;
  sessionBar: BarObservation;
}


export interface TradingSizingResult {
  disposition: "sized" | "hold";
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  quantity: number;
  issues: Array<TradingIssue>;
}


export interface TradingStrategyContext {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  asset: string;
  session: MarketSession;
  bars: Array<BarObservation>;
  observations: Array<Observation>;
  portfolioId: TradingId;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  cash: number;
  positions: Array<PortfolioPosition>;
}


export interface TradingStrategyData {
  manifest: TradingRunManifest;
  sessions: Array<MarketSession>;
  bars: Array<BarObservation>;
  actions: Array<CorporateActionObservation>;
  observations: Array<Observation>;
}


export interface TradingStrategyResultCosts {
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  commission: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  slippage: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  total: number;
}


export interface TradingStrategyResult {
  result: BacktestResult;
  days: Array<TradingDayResult>;
  portfolios: Array<PortfolioSnapshot>;
  fills: Array<Fill>;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  rejectedOrders: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  refusedObservations: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  staleMarks: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  writes: number;
  costs: TradingStrategyResultCosts;
}


export interface TradingStrategySignal {
  target: "long" | "flat";
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  availableAt: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  observationIds: Array<TradingId>;
}


export interface TradingStrategySignalOutcomeOneOf2 {
  valid: false;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  issues: Array<TradingIssue>;
}


export type TradingStrategySignalOutcome = { valid: true; value: TradingStrategySignal | null; } | TradingStrategySignalOutcomeOneOf2;

export interface TradingTimeRange {
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  from: string;
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  to: string;
}


export interface TradingVisiblePortfolio {
  id: TradingId;
  manifestId: TradingId;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  cash: number;
  positions: Array<PortfolioPosition>;
  asOfSessionId: TradingId | null;
}


export type Trading = TradingRecord;
