/** Immutable trading contracts; time, providers, persistence and execution are injected. */
export type * from './contracts.gen.ts';
export type * from './errors.ts';
export { tradingWorkflowIssue } from './errors.ts';
export type * from './records.ts';
export { tradingSchema, tradingSchemaOf, validateTradingShape } from './schema.ts';
export { createTradingRecord, validateTradingRecord } from './records.ts';
export { tradingRevisionOf, tradingIdentityOf } from './identity.ts';
export { sessionIndex, sessionAt, nextSession, cutoffFor, admit, latestBarsAsOf } from './time.ts';
export type { TradingSessionIndex, TradingAdmission } from './time.ts';
export { createTradingStoreAdapter, createMemoryTradingStore, planTradingCommit, TRADING_TABLES } from './store.ts';
export type * from './store.ts';
export { accountTradingFills, validateTradingLedger, validateInitialTradingPortfolio } from './accounting.ts';
export type { PortfolioState } from './accounting.ts';
export { adx, cci, vwap, volumeRatio, kdj } from './indicators.ts';
export { TRADING_SIGNAL_DEFAULTS, validateTradingSignalParameters, buyAndHold, macdCross, kdjRsi, zeroMeanReversion, smaCross } from './baselines.ts';
export type { TradingSignalSeries, TradingSignalPolicy } from './baselines.ts';
export { TRADING_PROVIDERS, createTradingProviderSnapshot, createFixtureProviders, createReplayProviders } from './providers.ts';
export type { TradingProviders, TradingProviderOutcome, TradingFixtureProviders } from './providers.ts';
export { buildSnapshot } from './snapshot.ts';
export type { TradingSnapshotInput, TradingSnapshotBundle } from './snapshot.ts';
export { planFill } from './broker.ts';
export { markPortfolio, applyCorporateActions } from './portfolio.ts';
export { checkRiskPolicy, sizeToPolicy } from './risk.ts';
export { runStrategy, equityCurve } from './strategy.ts';
export type { TradingStrategySignals, TradingStrategyDecisions, TradingStrategyInput } from './strategy.ts';
export { TRADING_ANALYST_ROLES, TRADING_ANALYST_TOOLS, prepareTradingAnalystContext, checkAnalystReport, buildAnalystRegion } from './analysts.ts';
export type { TradingAnalystContext, TradingAnalystProvenance, TradingAnalystRegion } from './analysts.ts';
export { TRADING_READ_TOOLS, createTradingReadTools } from './tools.ts';
export type { TradingToolAudit } from './tools.ts';
export { tradingArtifacts, tradingAnalystRegistry, createTradingHostBindings } from './host-bindings.ts';
export type { TradingHostInput } from './host-bindings.ts';
export { reportsToEvidence, researchInput } from './evidence.ts';
export { tradingResearchDomain, materializeResearch, researchVerdict } from './research.ts';
export type { TradingResearchContext, TradingAttemptProvenance } from './research.ts';
export { checkTradeProposal, buildResearchAndTraderRegion, createTradingResearchHostBindings } from './trader.ts';
export type { MaterializedTradingResearch } from './trader.ts';
export { TRADING_RISK_PERSONAS, initializeTradingRisk, checkRiskTurn, collectTradingRiskTurns, gateTradingRiskRound, finalizeTradingRisk } from './risk-tasks.ts';
export type { TradingRiskWorkflowInput, TradingRiskContext, TradingRiskProvenance } from './risk-tasks.ts';
export { buildRiskRound, buildRiskPattern, materializeTradingRisk, createTradingRiskHostBindings } from './risk-round.ts';
export type { MaterializedTradingRisk } from './risk-round.ts';
export { checkFundManagerDecision } from './fund-manager.ts';
export { toOrderIntent } from './order.ts';
export type { TradingOrderInput } from './order.ts';
export { buildRiskAndDecisionRegion, createTradingRiskDecisionHostBindings } from './risk-decision.ts';
export { buildTradingDecisionWorkflow, createTradingDecisionHostBindings } from './workflow.ts';
export type { TradingWorkflowInput, MaterializedTradingDecision } from './workflow.ts';
export { createDecisionRunner, tradingDecisionRunId } from './decision-runner.ts';
export type { TradingDecisionSegments, TradingDecisionRun, TradingDecisionRunnerInput } from './decision-runner.ts';
export { runBacktest } from './backtest.ts';
export type { TradingBacktestInput, TradingBacktestDecisionInput } from './backtest.ts';
