/** Immutable trading contracts; time, providers, persistence and execution are injected. */
export type * from './contracts.gen.ts';
export type * from './errors.ts';
export type * from './records.ts';
export { tradingSchema, tradingSchemaOf, validateTradingShape } from './schema.ts';
export { createTradingRecord, validateTradingRecord } from './records.ts';
export { tradingRevisionOf, tradingIdentityOf } from './identity.ts';
export { sessionIndex, sessionAt, nextSession, cutoffFor, admit, latestBarsAsOf } from './time.ts';
export type { TradingSessionIndex, TradingAdmission } from './time.ts';
export { createTradingStoreAdapter, createMemoryTradingStore, planTradingCommit, TRADING_TABLES } from './store.ts';
export type * from './store.ts';
export { accountTradingFills, validateTradingLedger, validateInitialTradingPortfolio } from './accounting.ts';
export type { PortfolioState } from './accounting.ts';
export { adx, cci, vwap, volumeRatio, kdj } from './indicators.ts';
export { TRADING_SIGNAL_DEFAULTS, validateTradingSignalParameters, buyAndHold, macdCross, kdjRsi, zeroMeanReversion, smaCross } from './baselines.ts';
export type { TradingSignalSeries, TradingSignalPolicy } from './baselines.ts';
export { TRADING_PROVIDERS, createTradingProviderSnapshot, createFixtureProviders, createReplayProviders } from './providers.ts';
export type { TradingProviders, TradingProviderOutcome, TradingFixtureProviders } from './providers.ts';
export { buildSnapshot } from './snapshot.ts';
export type { TradingSnapshotInput, TradingSnapshotBundle } from './snapshot.ts';
export { planFill } from './broker.ts';
export { markPortfolio, applyCorporateActions } from './portfolio.ts';
export { checkRiskPolicy, sizeToPolicy } from './risk.ts';
export { runStrategy, equityCurve } from './strategy.ts';
export type { TradingStrategySignals, TradingStrategyInput } from './strategy.ts';
