// Generated by @jarenjs/emit from packages/hera/schemas/hera.schema.json.
// Do not edit: regenerate instead.

export interface HeraIssue {
  code: "THERA1001" | "THERA1002" | "THERA1003" | "THERA1004" | "THERA1005" | "THERA1006" | "THERA1007" | "THERA1008" | "THERA1009";
  path: string;
  detail: string;
  cause?: unknown;
}


export type HeraMode = "learn" | "evaluate" | "infer";

export interface HeraBudget {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  tokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  ms: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  turns: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  nodes: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  depth: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  fanOut: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  concurrency: number;
}


export interface HeraUsage {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  promptTokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  completionTokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  unknownTokenRequests: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  estimatedTokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  ms: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  unknownMsRequests: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  embeddingRequests?: number;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraProfileTagsItem = string;

export interface HeraProfileEmbeddedBy {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  model: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  dims: number;
}


export interface HeraProfile {
  text: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  tags: Array<HeraProfileTagsItem>;
  embedding: Array<number>;
  embeddedBy: HeraProfileEmbeddedBy;
}


export interface HeraEvaluator {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  version: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  successRuleId: string;
}


export interface HeraLearningConfigSelectorWeights {
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  similarity: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  utility: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  novelty: number;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  selectionPenalty: number;
}


export interface HeraLearningConfigPromptBounds {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  maxRules: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  maxBytes: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  maxOps: number;
}


export interface HeraLearningConfig {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  groupSize: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  maxAgents: number;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  selectorVersion: string;
  selectorWeights: HeraLearningConfigSelectorWeights;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  selectorCap: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  libraryCap: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  operationCap: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  failureBufferSize: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  consecutiveFailures: number;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  variantAxes: Array<"efficiency" | "thoroughness" | "risk-sensitivity" | "error-correction" | "heuristic-injection">;
  promptBounds: HeraLearningConfigPromptBounds;
  flags: { experience: boolean; rope: boolean; mutation: boolean; };
}


/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type HeraHeadVersionIdAnyOf1 = string;

export interface HeraHead {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  kind: "library" | "prompt" | "snapshot";
  versionId: HeraHeadVersionIdAnyOf1 | null;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  revision: number;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraTaskProfileHintsItem = string;

export interface HeraTaskEvaluatorAnyOf1 {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  version: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  successRuleId: string;
}


export interface HeraTask {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  query: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  profileHints?: Array<HeraTaskProfileHintsItem>;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  corpusRevision: string;
  split: "training" | "held-out" | "unlabelled";
  evaluator: HeraTaskEvaluatorAnyOf1 | null;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  goldAddress?: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  outcomeAddress?: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraAgentDefinitionToolsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraAgentDefinitionContextAdaptersItem = string;

export interface HeraAgentDefinition {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  title: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  artifactId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  envelopeRevision: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  tools: Array<HeraAgentDefinitionToolsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  contextAdapters: Array<HeraAgentDefinitionContextAdaptersItem>;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  profile: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  activePromptVersionId: string;
  status: "active" | "archived";
}


/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type HeraPromptVersionParentIdAnyOf1 = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptVersionOperationalRulesItemDerivedFromItem = string;

export interface HeraPromptVersionOperationalRulesItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  derivedFrom: Array<HeraPromptVersionOperationalRulesItemDerivedFromItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptVersionBehavioralPrinciplesItemDerivedFromItem = string;

export interface HeraPromptVersionBehavioralPrinciplesItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  derivedFrom: Array<HeraPromptVersionBehavioralPrinciplesItemDerivedFromItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptVersionSourceTrialIdsItem = string;

export interface HeraPromptVersionSize {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  rules: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  bytes: number;
}


export interface HeraPromptVersion {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  agentId: string;
  parentId: HeraPromptVersionParentIdAnyOf1 | null;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  envelopeRevision: string;
  operationalRules: Array<HeraPromptVersionOperationalRulesItem>;
  behavioralPrinciples: Array<HeraPromptVersionBehavioralPrinciplesItem>;
  effectivePrompt: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  sourceTrialIds: Array<HeraPromptVersionSourceTrialIdsItem>;
  status: "candidate" | "active" | "rejected" | "archived";
  size: HeraPromptVersionSize;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  at: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  proposalOperationId?: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraTopologyProfileTagsItem = string;

export interface HeraTopologyProfileEmbeddedBy {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  model: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  dims: number;
}


export interface HeraTopologyProfile {
  text: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  tags: Array<HeraTopologyProfileTagsItem>;
  embedding: Array<number>;
  embeddedBy: HeraTopologyProfileEmbeddedBy;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraTopologyNodesItemDependsOnItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraTopologyNodesItemToolsItem = string;

export interface HeraTopologyNodesItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  agentId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  promptVersionId: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  dependsOn: Array<HeraTopologyNodesItemDependsOnItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  tools?: Array<HeraTopologyNodesItemToolsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraTopologyOfferedExperienceIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraTopologyAppliedExperienceIdsItem = string;

export interface HeraTopologyGenerator {
  kind: "fixed" | "orchestrator" | "mutation";
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  configRevision: string;
}


/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type HeraTopologyWorkflowVersionIdAnyOf1 = string;

/**
 * Schema constraints this type cannot express: $query={"$if":["$.validation.valid",{"$and":[{"$gt":[{"$count":"$.nodes"},0]},{"$and":[{"$eq":[{"$count":"$.nodes[*].id"},{"$count":{"$distinct":"$.nodes[*].id"}}]},{"$every":{"n":"$.nodes[*]"},"$satisfies":{"$every":{"dependency":"$n.dependsOn[*]"},"$satisfies":{"$some":{"other":"$.nodes[*]"},"$satisfies":{"$eq":["$other.id","$dependency"]}}}}]}]},true]}
 */
export interface HeraTopology {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  taskId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  snapshotId: string;
  profile: HeraTopologyProfile;
  /**
   * Schema constraints this type cannot express: minItems=0
   */
  nodes: Array<HeraTopologyNodesItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  offeredExperienceIds: Array<HeraTopologyOfferedExperienceIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  appliedExperienceIds: Array<HeraTopologyAppliedExperienceIdsItem>;
  generator: HeraTopologyGenerator;
  validation: { valid: boolean; issues: Array<HeraIssue>; };
  workflowVersionId: HeraTopologyWorkflowVersionIdAnyOf1 | null;
  rawProposal?: unknown;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraTrajectoryInvocationOrderItem = string;

/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type HeraTrajectoryClaimEnvelopeIdAnyOf1 = string;

export interface HeraTrajectoryCitationsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  digest: string;
}


/**
 * Schema constraints this type cannot express: minimum=0, maximum=1
 */
export type HeraTrajectoryPrimaryScoreAnyOf1 = number;

export interface HeraTrajectoryTokens {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  prompt: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  completion: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  unknownRequests: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  estimated: number;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraTrajectoryFailureAnyOf1NodeAnyOf1 = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraTrajectoryStepIdsItem = string;

export interface HeraTrajectoryMetrics {
  /**
   * Schema constraints this type cannot express: minimum=0, maximum=1
   */
  citationRecall: number;
  unsupported: Array<HeraIssue>;
  evaluator?: { [key: string]: number; };
}


export interface HeraTrajectory {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  taskId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  snapshotId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  topologyId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  masRunId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  groupId: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  invocationOrder: Array<HeraTrajectoryInvocationOrderItem>;
  answer: string;
  claimEnvelopeId: HeraTrajectoryClaimEnvelopeIdAnyOf1 | null;
  citations: Array<HeraTrajectoryCitationsItem>;
  primaryScore: HeraTrajectoryPrimaryScoreAnyOf1 | null;
  success: boolean | null;
  tokens: HeraTrajectoryTokens;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  stopReason: string;
  failure: { node: HeraTrajectoryFailureAnyOf1NodeAnyOf1 | null; issue: HeraIssue; } | null;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  stepIds: Array<HeraTrajectoryStepIdsItem>;
  status: "completed" | "failed" | "orphan" | "skipped";
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  identityId: string;
  metrics: HeraTrajectoryMetrics;
}


export interface HeraTrajectoryStepInputView {
  state: "retained" | "truncated" | "omitted";
  text: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  originalBytes: number;
}


export interface HeraTrajectoryStepTranscriptView {
  state: "retained" | "truncated" | "omitted";
  text: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  originalBytes: number;
}


export interface HeraTrajectoryStepToolStepsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  name: string;
  input: unknown;
  output: unknown;
  status: "completed" | "failed" | "uncertain";
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraTrajectoryStepEvidenceAddressesItem = string;

export interface HeraTrajectoryStepUsage {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  promptTokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  completionTokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  unknownTokenRequests: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  estimatedTokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  ms: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  unknownMsRequests: number;
}


export interface HeraTrajectoryStepSpend {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  tokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  ms: number;
}


export interface HeraTrajectoryStep {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  trajectoryId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  invocationId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  agentId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  promptVersionId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  masAttemptId: string;
  inputView: HeraTrajectoryStepInputView;
  transcriptView: HeraTrajectoryStepTranscriptView;
  toolSteps: Array<HeraTrajectoryStepToolStepsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  evidenceAddresses: Array<HeraTrajectoryStepEvidenceAddressesItem>;
  usage: HeraTrajectoryStepUsage;
  spend: HeraTrajectoryStepSpend;
  stopReason: string | null;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  at: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraRolloutGroupCandidateTrajectoryIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraRolloutGroupRankingItem = string;

export interface HeraRolloutGroupBudgetLimits {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  tokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  ms: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  turns: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  nodes: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  depth: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  fanOut: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  concurrency: number;
}


export interface HeraRolloutGroupBudgetSpent {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  tokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  ms: number;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraRolloutGroupOfferedExperienceIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraRolloutGroupTopologyIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraRolloutGroupOperationIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraRolloutGroupUnevaluatedTrajectoryIdsItem = string;

export interface HeraRolloutGroupRefusals {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  invalidCandidates: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  duplicateCandidates: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  appliedNotOffered: number;
}


export interface HeraRolloutGroup {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  taskId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  snapshotId: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  requestedSize: number;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  candidateTrajectoryIds: Array<HeraRolloutGroupCandidateTrajectoryIdsItem>;
  failures: Array<HeraIssue>;
  skips: Array<HeraIssue>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  ranking: Array<HeraRolloutGroupRankingItem>;
  mixedOutcome: { value: boolean; reason: string; };
  budget: { limits: HeraRolloutGroupBudgetLimits; spent: HeraRolloutGroupBudgetSpent; };
  state: "completed" | "failed" | "orphan";
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  configRevision?: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  requestBinding?: string;
  profile?: HeraProfile;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  offeredExperienceIds?: Array<HeraRolloutGroupOfferedExperienceIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  topologyIds?: Array<HeraRolloutGroupTopologyIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  operationIds?: Array<HeraRolloutGroupOperationIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  unevaluatedTrajectoryIds?: Array<HeraRolloutGroupUnevaluatedTrajectoryIdsItem>;
  controlUsage?: HeraUsage;
  refusals?: HeraRolloutGroupRefusals;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  groupIndex?: number;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraSemanticAdvantageSuccessFactorsItemTrajectoryIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraSemanticAdvantageSuccessFactorsItemStepIdsItem = string;

export interface HeraSemanticAdvantageSuccessFactorsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  trajectoryIds: Array<HeraSemanticAdvantageSuccessFactorsItemTrajectoryIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  stepIds: Array<HeraSemanticAdvantageSuccessFactorsItemStepIdsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraSemanticAdvantageFailureModesItemTrajectoryIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraSemanticAdvantageFailureModesItemStepIdsItem = string;

export interface HeraSemanticAdvantageFailureModesItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  trajectoryIds: Array<HeraSemanticAdvantageFailureModesItemTrajectoryIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  stepIds: Array<HeraSemanticAdvantageFailureModesItemStepIdsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraSemanticAdvantageInsightsItemTrajectoryIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraSemanticAdvantageInsightsItemStepIdsItem = string;

export interface HeraSemanticAdvantageInsightsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  trajectoryIds: Array<HeraSemanticAdvantageInsightsItemTrajectoryIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  stepIds: Array<HeraSemanticAdvantageInsightsItemStepIdsItem>;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraSemanticAdvantageFailedInvocationCreditItemStepIdsItem = string;

export interface HeraSemanticAdvantageFailedInvocationCreditItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  invocationId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  trajectoryId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reason: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  stepIds: Array<HeraSemanticAdvantageFailedInvocationCreditItemStepIdsItem>;
}


/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type HeraSemanticAdvantagePromptVersionIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraSemanticAdvantageSourceTrajectoryIdsItem = string;

export interface HeraSemanticAdvantage {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  groupId: string;
  successFactors: Array<HeraSemanticAdvantageSuccessFactorsItem>;
  failureModes: Array<HeraSemanticAdvantageFailureModesItem>;
  insights: Array<HeraSemanticAdvantageInsightsItem>;
  failedInvocationCredit: Array<HeraSemanticAdvantageFailedInvocationCreditItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  promptVersionIds: Array<HeraSemanticAdvantagePromptVersionIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  sourceTrajectoryIds: Array<HeraSemanticAdvantageSourceTrajectoryIdsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraExperienceProfileTagsItem = string;

export interface HeraExperienceProfileEmbeddedBy {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  model: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  dims: number;
}


export interface HeraExperienceProfile {
  text: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  tags: Array<HeraExperienceProfileTagsItem>;
  embedding: Array<number>;
  embeddedBy: HeraExperienceProfileEmbeddedBy;
}


export interface HeraExperienceProvenance {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  advantageId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  groupId: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraExperienceParentsItem = string;

export interface HeraExperienceInheritedCountsAnyOf1 {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  useCount: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  successCount: number;
}


/**
 * Schema constraints this type cannot express: $query={"$and":[{"$le":["$.successCount","$.useCount"]},{"$eq":["$.utility",{"$if":[{"$gt":["$.useCount",0]},{"$div":["$.successCount","$.useCount"]},0]}]},{"$eq":[{"$count":"$.insightEmbedding[*]"},"$.profile.embeddedBy.dims"]},{"$eq":[{"$count":"$.profile.embedding[*]"},"$.profile.embeddedBy.dims"]}]}
 */
export interface HeraExperience {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  profile: HeraExperienceProfile;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  insight: string;
  provenance: HeraExperienceProvenance;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  useCount: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  successCount: number;
  /**
   * Schema constraints this type cannot express: minimum=0, maximum=1
   */
  utility: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  selectionCount: number;
  status: "active" | "archived";
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  parents: Array<HeraExperienceParentsItem>;
  inheritedCounts: HeraExperienceInheritedCountsAnyOf1 | null;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  insightEmbedding: Array<number>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptTrialFailedInvocationIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptTrialBufferTrajectoryIdsItem = string;

/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type HeraPromptTrialCandidatePromptVersionIdAnyOf1 = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptTrialControlTrajectoryIdAnyOf1 = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptTrialReplayTrajectoryIdAnyOf1 = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptTrialOperationalRulesItemDerivedFromItem = string;

export interface HeraPromptTrialOperationalRulesItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  derivedFrom: Array<HeraPromptTrialOperationalRulesItemDerivedFromItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptTrialBehavioralPrinciplesItemDerivedFromItem = string;

export interface HeraPromptTrialBehavioralPrinciplesItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  derivedFrom: Array<HeraPromptTrialBehavioralPrinciplesItemDerivedFromItem>;
}


/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type HeraPromptTrialPinsActivePromptVersionIdsAdditional = string;

/**
 * Schema constraints this type cannot express: type="integer", minimum=0
 */
export type HeraPromptTrialPinsLimitsAdditional = number;

export interface HeraPromptTrialPins {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  taskId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  snapshotId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  corpusRevision: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  topologyId: string;
  activePromptVersionIds: { [key: string]: HeraPromptTrialPinsActivePromptVersionIdsAdditional; };
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  identityId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  evidenceRevision: string;
  contextAdapter: "documents" | "memory";
  limits: { [key: string]: HeraPromptTrialPinsLimitsAdditional; };
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptTrialExecutionRunIdsItem = string;

export interface HeraPromptTrial {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  agentId: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  failedInvocationIds: Array<HeraPromptTrialFailedInvocationIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  bufferTrajectoryIds: Array<HeraPromptTrialBufferTrajectoryIdsItem>;
  axis: "efficiency" | "thoroughness" | "risk-sensitivity" | "error-correction" | "heuristic-injection";
  candidatePromptVersionId: HeraPromptTrialCandidatePromptVersionIdAnyOf1 | null;
  controlTrajectoryId: HeraPromptTrialControlTrajectoryIdAnyOf1 | null;
  replayTrajectoryId: HeraPromptTrialReplayTrajectoryIdAnyOf1 | null;
  delta: { score: number; tokens: number; } | null;
  operationalRules: Array<HeraPromptTrialOperationalRulesItem>;
  behavioralPrinciples: Array<HeraPromptTrialBehavioralPrinciplesItem>;
  decision: "activated" | "rejected" | "malformed" | "unevaluated";
  reason: string;
  pins: HeraPromptTrialPins;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  bufferId: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  executionRunIds: Array<HeraPromptTrialExecutionRunIdsItem>;
}


/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type HeraLearningSnapshotParentIdAnyOf1 = string;

/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type HeraLearningSnapshotActivePromptVersionIdsAdditional = string;

/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type HeraLearningSnapshotExperienceIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraLearningSnapshotIdentitiesToolsItem = string;

export interface HeraLearningSnapshotIdentitiesEmbeddedBy {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  model: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  dims: number;
}


export interface HeraLearningSnapshotIdentitiesEvaluator {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  version: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  successRuleId: string;
}


export interface HeraLearningSnapshotIdentities {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  model: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  decoder: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  tools: Array<HeraLearningSnapshotIdentitiesToolsItem>;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  corpusRevision: string;
  embeddedBy: HeraLearningSnapshotIdentitiesEmbeddedBy;
  evaluator: HeraLearningSnapshotIdentitiesEvaluator;
}


/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type HeraLearningSnapshotFailureBufferIdsAdditional = string;

export interface HeraLearningSnapshot {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  parentId: HeraLearningSnapshotParentIdAnyOf1 | null;
  activePromptVersionIds: { [key: string]: HeraLearningSnapshotActivePromptVersionIdsAdditional; };
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  libraryRevision: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  experienceIds: Array<HeraLearningSnapshotExperienceIdsItem>;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  registryRevision: string;
  identities: HeraLearningSnapshotIdentities;
  config: HeraLearningConfig;
  status: "staged" | "active" | "archived";
  failureBufferIds?: { [key: string]: HeraLearningSnapshotFailureBufferIdsAdditional; };
}


export interface GmplCitation {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  digest: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
}


export interface GmplClaim {
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  citations: Array<GmplCitation>;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
}


export interface GmplFinding {
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  citations: Array<GmplCitation>;
  contradictory?: boolean;
  critical?: boolean;
  disposition: "supported" | "contested" | "rejected-with-reason" | "unresolved";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  origin: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reason: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraQueryDecomposerOutputOutstandingQuestionsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraQueryDecomposerOutputQueriesItem = string;

export interface HeraQueryDecomposerOutput {
  answer: string;
  claims: Array<GmplClaim>;
  disposition: "completed" | "no-consensus" | "needs-information" | "rejected";
  findings: Array<GmplFinding>;
  outstandingQuestions?: Array<HeraQueryDecomposerOutputOutstandingQuestionsItem>;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  queries: Array<HeraQueryDecomposerOutputQueriesItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraRetrieverOutputSelectedEvidenceIdsItem = string;

export interface HeraRetrieverOutput {
  answer: string;
  claims: Array<GmplClaim>;
  disposition: "completed" | "no-consensus" | "needs-information" | "rejected";
  findings: Array<GmplFinding>;
  outstandingQuestions?: Array<HeraQueryDecomposerOutputOutstandingQuestionsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  selectedEvidenceIds: Array<HeraRetrieverOutputSelectedEvidenceIdsItem>;
}


export interface HeraAnswerGeneratorOutput {
  answer: string;
  claims: Array<GmplClaim>;
  disposition: "completed" | "no-consensus" | "needs-information" | "rejected";
  findings: Array<GmplFinding>;
  outstandingQuestions?: Array<HeraQueryDecomposerOutputOutstandingQuestionsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraQueryRewriterOutputQueriesItem = string;

export interface HeraQueryRewriterOutput {
  answer: string;
  claims: Array<GmplClaim>;
  disposition: "completed" | "no-consensus" | "needs-information" | "rejected";
  findings: Array<GmplFinding>;
  outstandingQuestions?: Array<HeraQueryDecomposerOutputOutstandingQuestionsItem>;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  queries: Array<HeraQueryRewriterOutputQueriesItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraEvidenceSelectorOutputSelectedEvidenceIdsItem = string;

export interface HeraEvidenceSelectorOutput {
  answer: string;
  claims: Array<GmplClaim>;
  disposition: "completed" | "no-consensus" | "needs-information" | "rejected";
  findings: Array<GmplFinding>;
  outstandingQuestions?: Array<HeraQueryDecomposerOutputOutstandingQuestionsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  selectedEvidenceIds: Array<HeraEvidenceSelectorOutputSelectedEvidenceIdsItem>;
}


export interface HeraContextValidatorOutput {
  answer: string;
  claims: Array<GmplClaim>;
  disposition: "completed" | "no-consensus" | "needs-information" | "rejected";
  findings: Array<GmplFinding>;
  outstandingQuestions?: Array<HeraQueryDecomposerOutputOutstandingQuestionsItem>;
  sufficient: boolean;
  missing: Array<string>;
}


export interface HeraReflectAgentOutput {
  answer: string;
  claims: Array<GmplClaim>;
  disposition: "completed" | "no-consensus" | "needs-information" | "rejected";
  findings: Array<GmplFinding>;
  outstandingQuestions?: Array<HeraQueryDecomposerOutputOutstandingQuestionsItem>;
  problems: Array<string>;
}


export interface HeraConcludeAgentOutput {
  answer: string;
  claims: Array<GmplClaim>;
  disposition: "completed" | "no-consensus" | "needs-information" | "rejected";
  findings: Array<GmplFinding>;
  outstandingQuestions?: Array<HeraQueryDecomposerOutputOutstandingQuestionsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPlanOutputNodesItemDependsOnItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPlanOutputNodesItemToolsItem = string;

export interface HeraPlanOutputNodesItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  agentId: "query-decomposer" | "retriever" | "answer-generator" | "query-rewriter" | "evidence-selector" | "context-validator" | "reflect-agent" | "conclude-agent";
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  dependsOn: Array<HeraPlanOutputNodesItemDependsOnItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  tools?: Array<HeraPlanOutputNodesItemToolsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPlanOutputAppliedExperienceIdsItem = string;

export interface HeraPlanOutput {
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  nodes: Array<HeraPlanOutputNodesItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  appliedExperienceIds: Array<HeraPlanOutputAppliedExperienceIdsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraReflectionOutputSuccessFactorsItemTrajectoryIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraReflectionOutputSuccessFactorsItemStepIdsItem = string;

export interface HeraReflectionOutputSuccessFactorsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  trajectoryIds: Array<HeraReflectionOutputSuccessFactorsItemTrajectoryIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  stepIds: Array<HeraReflectionOutputSuccessFactorsItemStepIdsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraReflectionOutputFailureModesItemTrajectoryIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraReflectionOutputFailureModesItemStepIdsItem = string;

export interface HeraReflectionOutputFailureModesItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  trajectoryIds: Array<HeraReflectionOutputFailureModesItemTrajectoryIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  stepIds: Array<HeraReflectionOutputFailureModesItemStepIdsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraReflectionOutputInsightsItemTrajectoryIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraReflectionOutputInsightsItemStepIdsItem = string;

export interface HeraReflectionOutputInsightsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  trajectoryIds: Array<HeraReflectionOutputInsightsItemTrajectoryIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  stepIds: Array<HeraReflectionOutputInsightsItemStepIdsItem>;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraReflectionOutputFailedInvocationCreditItemStepIdsItem = string;

export interface HeraReflectionOutputFailedInvocationCreditItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  invocationId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  trajectoryId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reason: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  stepIds: Array<HeraReflectionOutputFailedInvocationCreditItemStepIdsItem>;
}


export interface HeraReflectionOutput {
  successFactors: Array<HeraReflectionOutputSuccessFactorsItem>;
  failureModes: Array<HeraReflectionOutputFailureModesItem>;
  insights: Array<HeraReflectionOutputInsightsItem>;
  failedInvocationCredit: Array<HeraReflectionOutputFailedInvocationCreditItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraConsolidationOutputOpsItemSourceInsightIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraConsolidationOutputOpsItemTargetIdsItem = string;

export interface HeraConsolidationOutputOpsItem {
  op: "ADD" | "MERGE" | "PRUNE" | "KEEP";
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  sourceInsightIds: Array<HeraConsolidationOutputOpsItemSourceInsightIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  targetIds: Array<HeraConsolidationOutputOpsItemTargetIdsItem>;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text?: string;
}


export interface HeraConsolidationOutput {
  ops: Array<HeraConsolidationOutputOpsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraRopeOutputOperationalRulesItemDerivedFromItem = string;

export interface HeraRopeOutputOperationalRulesItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  derivedFrom: Array<HeraRopeOutputOperationalRulesItemDerivedFromItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraRopeOutputBehavioralPrinciplesItemDerivedFromItem = string;

export interface HeraRopeOutputBehavioralPrinciplesItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  derivedFrom: Array<HeraRopeOutputBehavioralPrinciplesItemDerivedFromItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraRopeOutputDerivedFromItem = string;

export interface HeraRopeOutput {
  operationalRules: Array<HeraRopeOutputOperationalRulesItem>;
  behavioralPrinciples: Array<HeraRopeOutputBehavioralPrinciplesItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  derivedFrom: Array<HeraRopeOutputDerivedFromItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraMutationOutputDependsOnItem = string;

export interface HeraMutationOutput {
  action: "replace" | "augment";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  removeInvocationId?: string;
  addAgentId: "query-decomposer" | "retriever" | "answer-generator" | "query-rewriter" | "evidence-selector" | "context-validator" | "reflect-agent" | "conclude-agent";
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  dependsOn: Array<HeraMutationOutputDependsOnItem>;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reason: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraQueryProfileOutputTagsItem = string;

export interface HeraQueryProfileOutput {
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=32768
   */
  text: string;
  /**
   * Schema constraints this type cannot express: maxItems=16, uniqueItems=true
   */
  tags: Array<HeraQueryProfileOutputTagsItem>;
}


export type HeraOrchestratorOutput = HeraQueryProfileOutput | HeraPlanOutput;

export interface HeraOperation {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  taskId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  snapshotId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  groupId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  stage: string;
  phase: "dispatch" | "response" | "result";
  status: "pending" | "completed" | "failed" | "orphan" | "disabled";
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  binding: string;
  value: unknown;
  usage: HeraUsage;
  issues: Array<HeraIssue>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraProfileViewTagsItem = string;

export interface HeraProfileView {
  text: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  tags: Array<HeraProfileViewTagsItem>;
}


export interface HeraExperienceViewProvenance {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  advantageId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  groupId: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraExperienceViewParentsItem = string;

export interface HeraExperienceView {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  profile: HeraProfileView;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  insight: string;
  provenance: HeraExperienceViewProvenance;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  useCount: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  successCount: number;
  /**
   * Schema constraints this type cannot express: minimum=0, maximum=1
   */
  utility: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  selectionCount: number;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  parents: Array<HeraExperienceViewParentsItem>;
}


/**
 * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
 */
export type HeraFailureBufferParentIdAnyOf1 = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraFailureBufferEntriesItemStepIdsItem = string;

export interface HeraFailureBufferEntriesItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  trajectoryId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  invocationId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reason: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  advantageId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  groupId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  taskId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  snapshotId: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  stepIds: Array<HeraFailureBufferEntriesItemStepIdsItem>;
}


export interface HeraFailureBuffer {
  /**
   * Schema constraints this type cannot express: pattern="^[0-9a-f]{64}$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  agentId: string;
  parentId: HeraFailureBufferParentIdAnyOf1 | null;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  entries: Array<HeraFailureBufferEntriesItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptBlocksOperationalRulesItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptBlocksBehavioralPrinciplesItem = string;

export interface HeraPromptBlocks {
  operationalRules: Array<HeraPromptBlocksOperationalRulesItem>;
  behavioralPrinciples: Array<HeraPromptBlocksBehavioralPrinciplesItem>;
}


export interface HeraPromptPatchItemOneOf1 {
  op: "add";
  /**
   * Schema constraints this type cannot express: pattern="^/(operationalRules|behavioralPrinciples)/((0|[1-9][0-9]*)|-)$"
   */
  path: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  value: string;
}


export interface HeraPromptPatchItemOneOf2 {
  op: "replace";
  /**
   * Schema constraints this type cannot express: pattern="^/(operationalRules|behavioralPrinciples)/(0|[1-9][0-9]*)$"
   */
  path: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  value: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type HeraPromptPatchItemOneOf3ValueItem = string;

export interface HeraPromptPatchItemOneOf3 {
  op: "add" | "replace";
  /**
   * Schema constraints this type cannot express: pattern="^/(operationalRules|behavioralPrinciples)$"
   */
  path: string;
  value: Array<HeraPromptPatchItemOneOf3ValueItem>;
}


export interface HeraPromptPatchItemOneOf4 {
  op: "remove";
  /**
   * Schema constraints this type cannot express: pattern="^/(operationalRules|behavioralPrinciples)(/(0|[1-9][0-9]*))?$"
   */
  path: string;
}


export type HeraPromptPatch = Array<HeraPromptPatchItemOneOf1 | HeraPromptPatchItemOneOf2 | HeraPromptPatchItemOneOf3 | HeraPromptPatchItemOneOf4>;

export type Hera = unknown;
