# download the vscode extension: rest client (+5mil users)

### SearXNG GET query

@searxngUrl = http://localhost:8080

GET {{searxngUrl}}/search?format=json&q=vitamin+e


### SearXNG POST query

POST {{searxngUrl}}/search
content-type: application/x-www-form-urlencoded

q=What+are+the+benefits+of+using+Vitamine+E
&category_science=1
&pageno=1
&language=auto
&safesearch=0
&format=json

### Scraper Queries

@scraperUrl = http://localhost:3002

GET {{scraperUrl}}/api/scrape?kind=text/html&url=https://en.wikipedia.org/wiki/Vitamin_E


### Tangle-AI queries

@backendUrl = http://localhost:3001

### Get configuration

GET {{backendUrl}}/api/config
content-type: application/json

### request a websearch
POST {{backendUrl}}/api/search
content-type: application/json

{
    "query": "What are the benefits of using Vitamine E"
}

### request a newWebsearch
POST {{backendUrl}}/api/newsearch
content-type: application/json

{
    "query": "What are the benefits of using Vitamine E"
}

### request a fact-check
POST {{backendUrl}}/api/factcheck
content-type: application/json

{
    "query": "Vitamin E is vital for trees"
}

### request related images

POST {{backendUrl}}/api/images
content-type: application/json

{
    "query":"What are the benefits of vitamin e",
}

### request related videos

POST {{backendUrl}}/api/videos
content-type: application/json

{
    "query":"What are the benefits of vitamin e",
    "chat_history":[],
    "chat_model_provider":"ollama",
    "chat_model":"llama3.2:3b"
}
