// Generated by @jarenjs/emit.
// Do not edit: regenerate instead.

export type Json = null | boolean | number | string | Array<Json> | { [key: string]: Json; };

export type Reason = "invalid-time" | "unknown-validity" | "unanchored-relative" | "ambiguous-series" | "conflicting-claims" | "future-source" | "identity-mismatch" | "no-match" | "stale-projection" | "incomplete-index" | "provider-refusal" | "budget-exhausted" | "storage-failure" | "ordinary-query";

/**
 * Schema constraints this type cannot express: type="integer", minimum=0
 */
export type CoverageRefusalsAdditional = number;

export interface Coverage {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  occurrences: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  comparable: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  semanticCandidates: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  eligibleClaims: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  selected: number;
  poolTruncated: boolean;
  complete: boolean;
  refusals: { [key: string]: CoverageRefusalsAdditional; };
}


export interface Refusal {
  status: "refused" | "fallback";
  reason: Reason;
  detail: string;
  coverage?: Coverage;
}


export type Result = { status: "success"; value: Json; } | Refusal;

export interface Stamp {
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?(Z|[+-]\\d{2}:\\d{2})$"
   */
  at: string;
  raw: string;
  precision: "millisecond" | "second" | "minute" | "day" | "month" | "year";
  /**
   * Schema constraints this type cannot express: type="integer", minimum=-1439, maximum=1439
   */
  offsetMinutes: number;
  provenance: "explicit-offset" | "synthetic-UTC" | "host-asserted";
}


export interface EmbeddedBy {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  model: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  dims: number;
}


export interface SourceOccurrence {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  sessionOrdinal: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  turnOrdinal: number;
  role: "user" | "assistant" | "host";
  text: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  sourceHash: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sourceLocator: string;
  observedAt: Stamp;
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?(Z|[+-]\\d{2}:\\d{2})$"
   */
  knownAt: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  legacyMemoryId?: string;
}


export interface SourceSpan {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  sourceId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  sourceHash: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  start: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  end: number;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  quote: string;
}


export interface SeriesIdentity {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  subject: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  key: string;
}


export interface StateEndOneOf1 {
  kind: "at";
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?(Z|[+-]\\d{2}:\\d{2})$"
   */
  at: string;
}


export type StateEnd = StateEndOneOf1 | { kind: "open"; } | { kind: "unknown"; };

export interface ClaimTimeOneOf2 {
  kind: "point";
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?(Z|[+-]\\d{2}:\\d{2})$"
   */
  at: string;
  precision: "millisecond" | "second" | "minute" | "day";
}


export interface ClaimTimeOneOf3 {
  kind: "period";
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?(Z|[+-]\\d{2}:\\d{2})$"
   */
  from: string;
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?(Z|[+-]\\d{2}:\\d{2})$"
   */
  until: string;
  precision: "day" | "month" | "year";
}


export interface ClaimTimeOneOf4 {
  kind: "state";
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?(Z|[+-]\\d{2}:\\d{2})$"
   */
  from: string;
  until: StateEnd;
  precision: "millisecond" | "second" | "minute" | "day";
}


export type ClaimTime = { kind: "unknown"; } | ClaimTimeOneOf2 | ClaimTimeOneOf3 | ClaimTimeOneOf4;

export interface Derivation {
  method: "host-asserted" | "model" | "legacy-backfill";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  identity: string;
}


export interface TemporalClaim {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  series: SeriesIdentity;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  value: string;
  time: ClaimTime;
  status: "accepted" | "unknown" | "conflicting";
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  citations: Array<SourceSpan>;
  derivation: Derivation;
}


export interface KnowledgeOneOf2 {
  mode: "strict-as-of";
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?(Z|[+-]\\d{2}:\\d{2})$"
   */
  cutoff: string;
}


export type Knowledge = { mode: "provided-history"; } | KnowledgeOneOf2;

export interface ProjectionEmbedding {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  sourceId: string;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  vector: Array<number>;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
 */
export type TemporalProjectionOccurrenceIdsItem = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
 */
export type TemporalProjectionClaimIdsItem = string;

export interface TemporalProjection {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  versionId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sourceIdentity: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  viewIdentity: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  contractIdentity: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  policyIdentity: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  modelIdentity: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  promptIdentity: string;
  embeddedBy: EmbeddedBy;
  knowledge: Knowledge;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  occurrenceIds: Array<TemporalProjectionOccurrenceIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  claimIds: Array<TemporalProjectionClaimIdsItem>;
  embeddings: Array<ProjectionEmbedding>;
  complete: boolean;
}


export interface TemporalHead {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  versionId: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  revision: number;
}


export interface QueryOperationOneOf2 {
  kind: "at" | "as-of";
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?(Z|[+-]\\d{2}:\\d{2})$"
   */
  at: string;
}


export interface QueryOperationOneOf3 {
  kind: "overlaps";
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?(Z|[+-]\\d{2}:\\d{2})$"
   */
  from: string;
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?(Z|[+-]\\d{2}:\\d{2})$"
   */
  until: string;
}


export type QueryOperation = { kind: "none"; } | QueryOperationOneOf2 | QueryOperationOneOf3 | { kind: "elapsed"; fromSeries: SeriesIdentity; toSeries: SeriesIdentity; unit: "hour" | "day" | "week" | "month" | "year"; } | { kind: "order"; };

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type TemporalQuerySubjectAnyOf1 = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type TemporalQuerySeriesAnyOf1 = string;

export interface TemporalQuery {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  anchor: Stamp | null;
  knowledge: Knowledge;
  operation: QueryOperation;
  subject: TemporalQuerySubjectAnyOf1 | null;
  series: TemporalQuerySeriesAnyOf1 | null;
  embeddedBy: EmbeddedBy;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  embedding: Array<number>;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000
   */
  candidatePool: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=1000
   */
  k: number;
  /**
   * Schema constraints this type cannot express: minimum=-1, maximum=1
   */
  minScore: number;
  expectedHead: TemporalHead | null;
}


export interface ProjectionReceipt {
  head: TemporalHead;
  replayed: boolean;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  writes: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  activations: number;
}


/**
 * Schema constraints this type cannot express: type="integer", minimum=0
 */
export type PhysicalAttemptOutputTokensAnyOf1 = number;

export interface PhysicalAttempt {
  role: "extract" | "resolve" | "embedding" | "repair" | "answer" | "judge";
  phase: "in-flight" | "completed" | "failed" | "unknown";
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  inputTokens: number;
  outputTokens: PhysicalAttemptOutputTokensAnyOf1 | null;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  requestHash: string;
  reply: Json | null;
}


export interface TemporalOperation {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  key: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  requestIdentity: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  revision: number;
  phase: "reserved" | "in-flight" | "completed" | "failed" | "unknown";
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  maxPhysicalRequests: number;
  attempts: Array<PhysicalAttempt>;
  receipt: Json | null;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
 */
export type TemporalRecallClaimIdsItem = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
 */
export type TemporalRecallSourceIdsItem = string;

export interface TemporalRecall {
  head: TemporalHead;
  claimIds: Array<TemporalRecallClaimIdsItem>;
  sourceIds: Array<TemporalRecallSourceIdsItem>;
  claims: Array<TemporalClaim>;
  sources: Array<SourceOccurrence>;
  coverage: Coverage;
}


export interface TemporalAnswer {
  recall: TemporalRecall;
  operation: "at" | "as-of" | "overlaps" | "elapsed" | "order";
  value: Json;
  citations: Array<SourceSpan>;
  rule: string;
}


export interface CalendarWindow {
  from: string;
  until: string;
  precision: "day" | "month" | "year";
}


export interface ElapsedValue {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  whole: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  remainder: number;
  unit: "hour" | "day" | "week" | "month" | "year";
  remainderUnit: "millisecond" | "day";
}


export interface TemporalBundle {
  projection: TemporalProjection;
  sources: Array<SourceOccurrence>;
  claims: Array<TemporalClaim>;
}


export interface TemporalSnapshot {
  projection: TemporalProjection;
  sources: Array<SourceOccurrence>;
  claims: Array<TemporalClaim>;
  head: TemporalHead;
}


/**
 * Schema constraints this type cannot express: type="integer"
 */
export type TemporalClaimRowValidFromEpochMsAnyOf1 = number;

/**
 * Schema constraints this type cannot express: type="integer"
 */
export type TemporalClaimRowValidUntilEpochMsAnyOf1 = number;

export interface TemporalClaimRow {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  id: string;
  scope: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  versionId: string;
  subject: string;
  series: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  knownAtEpochMs: number;
  validFromEpochMs: TemporalClaimRowValidFromEpochMsAnyOf1 | null;
  validUntilEpochMs: TemporalClaimRowValidUntilEpochMsAnyOf1 | null;
  claim: TemporalClaim;
}


export interface TemporalStoreStats {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  writes: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  activations: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  transactions: number;
}


export interface TemporalLimits {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000000
   */
  maxInputTokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=1000000
   */
  maxOutputTokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0, maximum=10000
   */
  maxPhysicalRequests: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0, maximum=100000
   */
  maxSources: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0, maximum=100000
   */
  maxClaims: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=4
   */
  concurrency: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=120000
   */
  deadlineMs: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0, maximum=1
   */
  maxRepairs: number;
}


export type RelativeOperand = "yesterday" | "previous-week" | "previous-month" | "previous-year";

export interface ProposedTimeAnyOf2 {
  kind: "relative";
  operand: RelativeOperand;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sourceId: string;
}


export type ProposedTime = ClaimTime | ProposedTimeAnyOf2;

export interface ClaimProposal {
  series: SeriesIdentity;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  value: string;
  time: ProposedTime;
  status: "accepted" | "unknown" | "conflicting";
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  citations: Array<SourceSpan>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type ExtractionProposalCoveredSourceIdsItem = string;

export interface ExtractionProposal {
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  coveredSourceIds: Array<ExtractionProposalCoveredSourceIdsItem>;
  claims: Array<ClaimProposal>;
}


export interface QuerySpan {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0, maximum=10000000
   */
  start: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000000
   */
  end: number;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  quote: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type QueryProposalSubjectAnyOf1 = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type QueryProposalSeriesAnyOf1 = string;

export interface QueryProposal {
  subject: QueryProposalSubjectAnyOf1 | null;
  series: QueryProposalSeriesAnyOf1 | null;
  operation: QueryOperation | { kind: "relative"; operand: RelativeOperand; };
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  citations: Array<QuerySpan>;
}


/**
 * Schema constraints this type cannot express: minimum=-180, maximum=180
 */
export type PositionItem1 = number;

/**
 * Schema constraints this type cannot express: minimum=-90, maximum=90
 */
export type PositionItem2 = number;

/**
 * Schema constraints this type cannot express: minItems=2, maxItems=2
 */
export type Position = [PositionItem1, PositionItem2];

export interface PlaceGeometry {
  type: "Point";
  coordinates: Position;
}


export interface PlaceSource {
  kind: "wikidata" | "geonames";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: pattern="^https?://[^\\s]+$"
   */
  url: string;
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}$"
   */
  retrieved: string;
}


export interface PlaceSourceLatLon {
  /**
   * Schema constraints this type cannot express: minimum=-90, maximum=90
   */
  lat: number;
  /**
   * Schema constraints this type cannot express: minimum=-180, maximum=180
   */
  lon: number;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GazetteerEntryNamesItem = string;

export interface GazetteerEntry {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  names: Array<GazetteerEntryNamesItem>;
  geometry: PlaceGeometry;
  sourceLatLon: PlaceSourceLatLon;
  source: PlaceSource;
  confidence: "exact" | "settlement" | "region";
}


export interface Gazetteer {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: minItems=0
   */
  entries: Array<GazetteerEntry>;
}


export interface PlaceMentionOneOf1 {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  sourceId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  sourceHash: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  start: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  end: number;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  quote: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  entryId: GazetteerEntryNamesItem;
  status: "grounded";
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  candidates: Array<GazetteerEntryNamesItem>;
}


export interface PlaceMentionOneOf2 {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  sourceId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  sourceHash: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  start: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  end: number;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  quote: string;
  entryId: null;
  status: "ambiguous";
  /**
   * Schema constraints this type cannot express: minItems=2, uniqueItems=true
   */
  candidates: Array<GazetteerEntryNamesItem>;
}


export interface PlaceMentionOneOf3 {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  sourceId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  sourceHash: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  start: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  end: number;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  quote: string;
  entryId: null;
  status: "ungrounded";
  /**
   * Schema constraints this type cannot express: minItems=0, maxItems=0, uniqueItems=true
   */
  candidates: Array<GazetteerEntryNamesItem>;
}


/**
 * Schema constraints this type cannot express: $query={"$and":[{"$lt":["$.start","$.end"]},{"$or":[{"$ne":["$.status",{"$const":"grounded"}]},{"$exists":{"$index-of":["$.candidates[*]","$.entryId"]}}]}]}
 */
export type PlaceMention = PlaceMentionOneOf1 | PlaceMentionOneOf2 | PlaceMentionOneOf3;

export interface PlaceIntent {
  proximity: boolean;
  spatial: boolean;
}


export type PlaceCode = "TPLC1001" | "TPLC1002" | "TPLC1003" | "TPLC1004" | "TPLC1005" | "TPLC1006" | "TPLC1007" | "TPLC1008" | "TPLC1009" | "TPLC1010" | "TPLC1011";

export type PlaceReason = "invalid-shape" | "invalid-geometry" | "unsourced-coordinate" | "unknown-entry" | "ungrounded-mention" | "ambiguous-place" | "spatial-gate" | "no-position-at-instant" | "temporal-refusal" | "storage-failure" | "budget-exhausted";

export interface PlaceCoverage {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0, maximum=9007199254740991
   */
  occurrences: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0, maximum=9007199254740991
   */
  comparable: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0, maximum=9007199254740991
   */
  semanticCandidates: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0, maximum=9007199254740991
   */
  positions: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0, maximum=9007199254740991
   */
  unplaceable: number;
  poolTruncated: boolean;
  complete: boolean;
}


export interface PlaceRefusalOneOf1 {
  status: "refused";
  code: "TPLC1001";
  reason: "invalid-shape";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  cause?: GazetteerEntryNamesItem;
  coverage?: PlaceCoverage;
}


export interface PlaceRefusalOneOf2 {
  status: "refused";
  code: "TPLC1002";
  reason: "invalid-geometry";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  cause?: GazetteerEntryNamesItem;
  coverage?: PlaceCoverage;
}


export interface PlaceRefusalOneOf3 {
  status: "refused";
  code: "TPLC1003";
  reason: "unsourced-coordinate";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  cause?: GazetteerEntryNamesItem;
  coverage?: PlaceCoverage;
}


export interface PlaceRefusalOneOf4 {
  status: "refused";
  code: "TPLC1004";
  reason: "unknown-entry";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  cause?: GazetteerEntryNamesItem;
  coverage?: PlaceCoverage;
}


export interface PlaceRefusalOneOf5 {
  status: "refused";
  code: "TPLC1005";
  reason: "ungrounded-mention";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  cause?: GazetteerEntryNamesItem;
  coverage?: PlaceCoverage;
}


export interface PlaceRefusalOneOf6 {
  status: "refused";
  code: "TPLC1006";
  reason: "ambiguous-place";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  cause?: GazetteerEntryNamesItem;
  coverage?: PlaceCoverage;
}


export interface PlaceRefusalOneOf7 {
  status: "refused";
  code: "TPLC1007";
  reason: "spatial-gate";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  cause?: GazetteerEntryNamesItem;
  coverage?: PlaceCoverage;
}


export interface PlaceRefusalOneOf8 {
  status: "refused";
  code: "TPLC1008";
  reason: "no-position-at-instant";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  cause?: GazetteerEntryNamesItem;
  coverage?: PlaceCoverage;
}


export interface PlaceRefusalOneOf9 {
  status: "refused";
  code: "TPLC1009";
  reason: "temporal-refusal";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  cause?: GazetteerEntryNamesItem;
  coverage?: PlaceCoverage;
}


export interface PlaceRefusalOneOf10 {
  status: "refused";
  code: "TPLC1010";
  reason: "storage-failure";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  cause?: GazetteerEntryNamesItem;
  coverage?: PlaceCoverage;
}


export interface PlaceRefusalOneOf11 {
  status: "refused";
  code: "TPLC1011";
  reason: "budget-exhausted";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  cause?: GazetteerEntryNamesItem;
  coverage?: PlaceCoverage;
}


export type PlaceRefusal = PlaceRefusalOneOf1 | PlaceRefusalOneOf2 | PlaceRefusalOneOf3 | PlaceRefusalOneOf4 | PlaceRefusalOneOf5 | PlaceRefusalOneOf6 | PlaceRefusalOneOf7 | PlaceRefusalOneOf8 | PlaceRefusalOneOf9 | PlaceRefusalOneOf10 | PlaceRefusalOneOf11;

/**
 * Schema constraints this type cannot express: type="integer", minimum=1, maximum=12
 */
export type GeohashPrecision = number;

export interface PositionSample {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  claimId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  entryId: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  at: GazetteerEntryNamesItem;
  until: GazetteerEntryNamesItem | null;
  kind: "state" | "event";
}


export interface PlaceOperationOneOf1 {
  kind: "location-at";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  at: GazetteerEntryNamesItem;
}


export interface PlaceOperationOneOf2 {
  kind: "location-at-event";
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  eventClaimId: string;
}


export interface PlaceOperationOneOf3 {
  kind: "movement";
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  fromClaimId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  toClaimId: string;
}


export interface PlaceOperationOneOf4 {
  kind: "nearby";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  entryId: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  radiusMetres: number;
  precision: GeohashPrecision;
}


export type PlaceOperation = PlaceOperationOneOf1 | PlaceOperationOneOf2 | PlaceOperationOneOf3 | PlaceOperationOneOf4;

export interface PlaceQuery {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  scope: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  subject: GazetteerEntryNamesItem;
  operation: PlaceOperation;
  knowledge: Knowledge;
  embeddedBy: EmbeddedBy;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  embedding: Array<number>;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=10000
   */
  candidatePool: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=1000
   */
  k: number;
  /**
   * Schema constraints this type cannot express: minimum=-1, maximum=1
   */
  minScore: number;
  expectedHead: TemporalHead | null;
}


/**
 * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
 */
export type PlaceAnswerOneOf1ClaimIdsItem = string;

export interface PlaceAnswerOneOf1 {
  kind: "location-at" | "location-at-event";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  entryId: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  claimIds: Array<PlaceAnswerOneOf1ClaimIdsItem>;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  sourceIds: Array<PlaceAnswerOneOf1ClaimIdsItem>;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  citations: Array<SourceSpan>;
}


export interface PlaceAnswerOneOf2 {
  kind: "movement";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  fromEntryId: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  toEntryId: GazetteerEntryNamesItem;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0, maximum=9007199254740991
   */
  metres: number;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  claimIds: Array<PlaceAnswerOneOf1ClaimIdsItem>;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  sourceIds: Array<PlaceAnswerOneOf1ClaimIdsItem>;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  citations: Array<SourceSpan>;
}


export interface PlaceAnswerOneOf3 {
  kind: "nearby";
  /**
   * Schema constraints this type cannot express: minItems=0, uniqueItems=true
   */
  entryIds: Array<GazetteerEntryNamesItem>;
  /**
   * Schema constraints this type cannot express: minItems=0, uniqueItems=true
   */
  claimIds: Array<PlaceAnswerOneOf1ClaimIdsItem>;
  /**
   * Schema constraints this type cannot express: minItems=0, uniqueItems=true
   */
  sourceIds: Array<PlaceAnswerOneOf1ClaimIdsItem>;
  /**
   * Schema constraints this type cannot express: minItems=0, uniqueItems=true
   */
  citations: Array<SourceSpan>;
}


export type PlaceAnswer = PlaceAnswerOneOf1 | PlaceAnswerOneOf2 | PlaceAnswerOneOf3;

export type PlaceContracts = Gazetteer;
