// Generated by @jarenjs/emit from packages/grounding/schemas/grounding.schema.json.
// Do not edit: regenerate instead.

export type AuthorityTier = "official" | "professional" | "community" | "unverified";

export type TimeProvenance = "content" | "metadata" | "curator";

export interface GroundingIssueCause {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  code: string;
  docPath: string;
  message: string;
}


export interface GroundingIssue {
  code: "TGRD1001" | "TGRD1002" | "TGRD1003" | "TGRD1004" | "TGRD1005" | "TGRD1006" | "TGRD1007" | "TGRD1008" | "TGRD1009" | "TGRD1010";
  path: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: string;
  cause?: GroundingIssueCause;
}


export interface GroundingSpend {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  tokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  ms: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  searches: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  fetches: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  bytes: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  clarificationTurns: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  contextTokens: number;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundingProfileLocalesItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundingProfilePurposesItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundingProfileEmergencyPatternsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundingProfileEmergencyResponseSourceKeysItem = string;

export interface GroundingProfileEmergencyResponse {
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  sourceKeys: Array<GroundingProfileEmergencyResponseSourceKeysItem>;
}


export interface GroundingProfileEmergency {
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  patterns: Array<GroundingProfileEmergencyPatternsItem>;
  response: GroundingProfileEmergencyResponse;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundingProfileOutOfScopeItemPatternsItem = string;

export interface GroundingProfileOutOfScopeItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  category: "diagnosis" | "prescribing" | "dosage" | "certainty";
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  patterns: Array<GroundingProfileOutOfScopeItemPatternsItem>;
}


export interface GroundingProfileAuthorityHostsItem {
  /**
   * Schema constraints this type cannot express: pattern="^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$"
   */
  host: string;
  /**
   * Schema constraints this type cannot express: pattern="^/[^?#]*$"
   */
  pathPrefix?: string;
  tier: AuthorityTier;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  institution: string;
}


export interface GroundingProfileFreshness {
  requireProvenance: true;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  maxAgeDays?: number;
  preferEffectiveOverFetch: true;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundingProfileExpansionsItemWhenIntentsItem = string;

export interface GroundingProfileExpansionsItemWhen {
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  intents: Array<GroundingProfileExpansionsItemWhenIntentsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundingProfileExpansionsItemAddQueriesItem = string;

export interface GroundingProfileExpansionsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  when: GroundingProfileExpansionsItemWhen;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  addQueries: Array<GroundingProfileExpansionsItemAddQueriesItem>;
}


export interface GroundingProfileModels {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  triage: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  plan: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reconcile: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  generate: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundingProfileClarificationRequiredFieldsItemIntentsItem = string;

export interface GroundingProfileClarificationRequiredFieldsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  intents: Array<GroundingProfileClarificationRequiredFieldsItemIntentsItem>;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  question: string;
  kind: "constraint" | "priority" | "context";
}


export interface GroundingProfileClarification {
  requiredFields: Array<GroundingProfileClarificationRequiredFieldsItem>;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  maxTurns: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=32
   */
  maxQueries: number;
}


export interface GroundingProfileRankers {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  local: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  web: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundingProfileUserContextCollectableItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundingProfileUserContextPersistableItem = string;

export interface GroundingProfileUserContext {
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  collectable: Array<GroundingProfileUserContextCollectableItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  persistable: Array<GroundingProfileUserContextPersistableItem>;
}


export interface GroundingProfile {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  version: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  revision: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  jurisdiction: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  locales: Array<GroundingProfileLocalesItem>;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  purposes: Array<GroundingProfilePurposesItem>;
  emergency: GroundingProfileEmergency;
  outOfScope: Array<GroundingProfileOutOfScopeItem>;
  authority: { tiers: ["official","professional","community","unverified"]; hosts: Array<GroundingProfileAuthorityHostsItem>; };
  freshness: GroundingProfileFreshness;
  expansions: Array<GroundingProfileExpansionsItem>;
  models: GroundingProfileModels;
  clarification: GroundingProfileClarification;
  rankers: GroundingProfileRankers;
  budgets: GroundingSpend;
  userContext: GroundingProfileUserContext;
}


/**
 * Schema constraints this type cannot express: if={"properties":{"provenance":{"type":"null"}}}, then={"properties":{"publishedAt":false,"effectiveAt":false,"expiresAt":false,"reviewedAt":false}}
 */
export type EvidenceTimesPart1 = unknown;

export type EvidenceTimes = EvidenceTimesPart1 & { publishedAt?: string; effectiveAt?: string; expiresAt?: string; reviewedAt?: string; provenance: TimeProvenance | null; };

export interface ManifestTimes {
  /**
   * Schema constraints this type cannot express: pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$", format="date-time"
   */
  publishedAt?: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$", format="date-time"
   */
  effectiveAt?: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$", format="date-time"
   */
  expiresAt?: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$", format="date-time"
   */
  reviewedAt?: string;
  provenance: TimeProvenance;
}


export interface CorpusManifestCurator {
  decision: "admit" | "supersede" | "promote";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  by: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$", format="date-time"
   */
  at: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  note?: string;
}


export interface CorpusManifest {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  profileId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  profileRevision: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sourceId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  versionId: string;
  status: "active" | "superseded";
  /**
   * Schema constraints this type cannot express: pattern="^https?://[^@?#\\s]+(?:\\?[^#\\s]*)?$"
   */
  canonicalUrl: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  institution: string;
  authorityTier: AuthorityTier;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  jurisdiction: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  language: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  contentHash: string;
  times: ManifestTimes;
  curator: CorpusManifestCurator;
}


export type SessionStatus = "open" | "triaging" | "awaiting_clarification" | "planning" | "retrieving" | "reconciling" | "generating" | "answered" | "refused" | "failed";

/**
 * Schema constraints this type cannot express: minLength=1, maxLength=1000
 */
export type GroundingSessionUserContextAdditional = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundingSessionAnswerIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type TriageDecisionRequiredFieldsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type TriageDecisionIntentsItem = string;

export interface TriageDecision {
  triage: "simple" | "complex";
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=2000
   */
  reason: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  requiredFields: Array<TriageDecisionRequiredFieldsItem>;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  intents: Array<TriageDecisionIntentsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type OptimizerCheckpointRuleIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type OptimizerCheckpointSourceKeysItem = string;

export interface OptimizerCheckpointBudget {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  tokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  ms: number;
}


export interface OptimizerCheckpointSpent {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  calls: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  tokens: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  ms: number;
}


export interface OptimizerCheckpoint {
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=16000
   */
  originalQuery: string;
  route: "simple" | "complex" | "emergency" | "out_of_scope";
  decision: TriageDecision | null;
  stage: "triaged" | "clarifying" | "ready" | "planned" | "refused" | "failed";
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  ruleIds: Array<OptimizerCheckpointRuleIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  sourceKeys: Array<OptimizerCheckpointSourceKeysItem>;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  catalogRevision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  vocabularyRevision: string;
  models: { triage: unknown; plan: unknown; };
  budget: OptimizerCheckpointBudget;
  spent: OptimizerCheckpointSpent;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  runId?: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  intentId?: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  stopReason?: string;
  issue?: GroundingIssue;
  inFlight?: "triage" | "clarify" | "plan";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  planId?: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  startRevision: number;
}


export interface GroundingSession {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  conversationId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  profileId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  profileRevision: string;
  status: SessionStatus;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  turn: number;
  /**
   * Schema constraints this type cannot express: propertyNames={"pattern":"^[a-z][a-zA-Z0-9_-]{0,63}$"}
   */
  userContext: { [key: string]: GroundingSessionUserContextAdditional; };
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  intentId?: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  planId?: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  answerIds: Array<GroundingSessionAnswerIdsItem>;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  revision: number;
  optimization?: OptimizerCheckpoint;
}


/**
 * Schema constraints this type cannot express: minLength=1, maxLength=1000
 */
export type ClarifiedIntentAnsweredAdditional = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type ClarifiedIntentOutstandingItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type ClarifiedIntentConstraintsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type ClarifiedIntentPrioritiesItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type ClarifiedIntentRuleIdsItem = string;

export interface ClarifiedIntent {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sessionId: string;
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=16000
   */
  originalQuery: string;
  triage: "simple" | "complex" | "emergency" | "out_of_scope";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reason: string;
  /**
   * Schema constraints this type cannot express: propertyNames={"pattern":"^[a-z][a-zA-Z0-9_-]{0,63}$"}
   */
  answered: { [key: string]: ClarifiedIntentAnsweredAdditional; };
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  outstanding: Array<ClarifiedIntentOutstandingItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  constraints: Array<ClarifiedIntentConstraintsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  priorities: Array<ClarifiedIntentPrioritiesItem>;
  /**
   * Schema constraints this type cannot express: maxLength=4000
   */
  summary: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  turnsUsed: number;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  ruleIds: Array<ClarifiedIntentRuleIdsItem>;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  promptRevision: string;
  modelIdentity: unknown;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type QueryPlanQueriesItemRuleIdsItem = string;

export interface QueryPlanQueriesItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=2000
   */
  text: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  why: string;
  lanes: { local: boolean; web: boolean; };
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  ruleIds: Array<QueryPlanQueriesItemRuleIdsItem>;
}


export interface QueryPlan {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  intentId: string;
  /**
   * Schema constraints this type cannot express: minItems=1, maxItems=32
   */
  queries: Array<QueryPlanQueriesItem>;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  promptRevision: string;
  modelIdentity: unknown;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  profileRevision?: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type EvidenceCitationHeadingPathItem = string;

export interface EvidenceCitation {
  /**
   * Schema constraints this type cannot express: pattern="^https?://[^@?#\\s]+(?:\\?[^#\\s]*)?$"
   */
  url: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  title: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  page?: number;
  headingPath: Array<EvidenceCitationHeadingPathItem>;
}


export interface LocalEvidenceAddress {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  chunkId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  parentChunkId?: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  versionId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sourceId: string;
}


/**
 * Schema constraints this type cannot express: pattern="^https?://[^@?#\\s]+(?:\\?[^#\\s]*)?$"
 */
export type WebEvidenceAddressRedirectsItem = string;

export interface WebEvidenceAddress {
  /**
   * Schema constraints this type cannot express: pattern="^https?://[^@?#\\s]+(?:\\?[^#\\s]*)?$"
   */
  url: string;
  /**
   * Schema constraints this type cannot express: pattern="^https?://[^@?#\\s]+(?:\\?[^#\\s]*)?$"
   */
  finalUrl: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  sha256: string;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$", format="date-time"
   */
  fetchedAt: string;
  redirects: Array<WebEvidenceAddressRedirectsItem>;
}


/**
 * Schema constraints this type cannot express: if={"properties":{"lane":{"const":"local"}}}, then={"properties":{"address":{"$ref":"#/$defs/localEvidenceAddress"}}}, else={"properties":{"address":{"$ref":"#/$defs/webEvidenceAddress"}}}
 */
export type EvidenceCandidatePart1 = unknown;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type EvidenceCandidateAuthorityRuleIdsItem = string;

export interface EvidenceCandidateAuthority {
  tier: AuthorityTier;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  institution?: string;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  ruleIds: Array<EvidenceCandidateAuthorityRuleIdsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type EvidenceCandidateAdmittedByItem = string;

export interface EvidenceCandidateAdmitted {
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  by: Array<EvidenceCandidateAdmittedByItem>;
  /**
   * Schema constraints this type cannot express: pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$", format="date-time"
   */
  at: string;
}


export type EvidenceCandidate = EvidenceCandidatePart1 & { id: string; sessionId: string; profileRevision: string; queryId: string; lane: "local" | "web"; address: LocalEvidenceAddress | WebEvidenceAddress; excerpt: string; scores: { semantic?: number; lexical?: number; fusion?: number; rank?: number; }; rankerId: string; authority: EvidenceCandidateAuthority; times: EvidenceTimes; admitted: EvidenceCandidateAdmitted; citation: EvidenceCitation; };

/**
 * Schema constraints this type cannot express: pattern="^https?://[^@?#\\s]+(?:\\?[^#\\s]*)?$"
 */
export type WebRetrievalRunAttemptsItemAdmittedItem = string;

export interface WebRetrievalRunAttemptsItemDeniedItem {
  url: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reason: string;
}


/**
 * Schema constraints this type cannot express: pattern="^https?://[^@?#\\s]+(?:\\?[^#\\s]*)?$"
 */
export type WebRetrievalRunAttemptsItemFetchedItemRedirectsItem = string;

export interface WebRetrievalRunAttemptsItemFetchedItem {
  /**
   * Schema constraints this type cannot express: pattern="^https?://[^@?#\\s]+(?:\\?[^#\\s]*)?$"
   */
  url: string;
  /**
   * Schema constraints this type cannot express: pattern="^https?://[^@?#\\s]+(?:\\?[^#\\s]*)?$"
   */
  finalUrl: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  sha256: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  bytes: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=100, maximum=599
   */
  status: number;
  redirects?: Array<WebRetrievalRunAttemptsItemFetchedItemRedirectsItem>;
}


export interface WebRetrievalRunAttemptsItemFailedItem {
  url: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  code: string;
}


export interface WebRetrievalRunAttemptsItem {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  query: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  results: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  snippets: number;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  admitted: Array<WebRetrievalRunAttemptsItemAdmittedItem>;
  denied: Array<WebRetrievalRunAttemptsItemDeniedItem>;
  fetched: Array<WebRetrievalRunAttemptsItemFetchedItem>;
  failed: Array<WebRetrievalRunAttemptsItemFailedItem>;
}


export interface WebRetrievalRunSufficiency {
  decision: "sufficient" | "insufficient" | "refused";
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  reason: string;
}


export interface WebRetrievalRun {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sessionId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  queryId: string;
  attempts: Array<WebRetrievalRunAttemptsItem>;
  sufficiency: WebRetrievalRunSufficiency;
  spend: GroundingSpend;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  stopReason: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type EvidenceConflictClaimIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type EvidenceConflictEvidenceIdsItem = string;

export interface EvidenceConflictComparison {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  authority: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  time: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type EvidenceConflictRuleIdsItem = string;

export interface EvidenceConflict {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sessionId: string;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  claimIds: Array<EvidenceConflictClaimIdsItem>;
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  evidenceIds: Array<EvidenceConflictEvidenceIdsItem>;
  issue: "stale-vs-newer" | "official-vs-unofficial" | "official-vs-official" | "expired" | "jurisdiction";
  comparison: EvidenceConflictComparison;
  severity: "critical" | "material" | "minor";
  decision: "prefer-local" | "prefer-web" | "caveat" | "refuse" | "unresolved";
  /**
   * Schema constraints this type cannot express: minItems=1, uniqueItems=true
   */
  ruleIds: Array<EvidenceConflictRuleIdsItem>;
  modelIdentity: unknown;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundedClaimEvidenceIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundedClaimConflictIdsItem = string;

/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundedClaimCaveatsItem = string;

export interface GroundedClaim {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  text: string;
  critical: boolean;
  status: "supported" | "qualified" | "unresolved" | "removed";
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  evidenceIds: Array<GroundedClaimEvidenceIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  conflictIds: Array<GroundedClaimConflictIdsItem>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  caveats: Array<GroundedClaimCaveatsItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type AnswerCitationHeadingPathItem = string;

export interface AnswerCitation {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  evidenceId: string;
  /**
   * Schema constraints this type cannot express: pattern="^https?://[^@?#\\s]+(?:\\?[^#\\s]*)?$"
   */
  url: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  title: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  page?: number;
  headingPath: Array<AnswerCitationHeadingPathItem>;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundedAnswerCaveatsItem = string;

export interface GroundedAnswerValidation {
  valid: boolean;
  issues: Array<GroundingIssue>;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  repairs: number;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundedAnswerIdentitiesRankerIdsItem = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
 */
export type GroundedAnswerIdentitiesConfigIdentityIdOneOf1 = string;

export interface GroundedAnswerIdentities {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  profileRevision: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  promptRevision: string;
  modelIdentity: unknown;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  rankerIds: Array<GroundedAnswerIdentitiesRankerIdsItem>;
  configIdentityId: GroundedAnswerIdentitiesConfigIdentityIdOneOf1 | null;
}


export interface GroundedAnswer {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  id: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  sessionId: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  planId: string | null;
  disposition: "answer" | "abstain" | "refuse" | "clarification";
  claims: Array<GroundedClaim>;
  citations: Array<AnswerCitation>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  caveats: Array<GroundedAnswerCaveatsItem>;
  validation: GroundedAnswerValidation;
  identities: GroundedAnswerIdentities;
  spend: GroundingSpend;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  stopReason: string;
}


/**
 * Schema constraints this type cannot express: minLength=1
 */
export type GroundingTraceUnusedItem = string;

export interface GroundingTrace {
  session: GroundingSession;
  profile: GroundingProfile;
  intents: Array<ClarifiedIntent>;
  plans: Array<QueryPlan>;
  evidence: Array<EvidenceCandidate>;
  webRuns: Array<WebRetrievalRun>;
  conflicts: Array<EvidenceConflict>;
  answers: Array<GroundedAnswer>;
  /**
   * Schema constraints this type cannot express: uniqueItems=true
   */
  unused: Array<GroundingTraceUnusedItem>;
}


export interface QueryDraftQueriesItem {
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=2000
   */
  text: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  why: string;
  lanes: { local: boolean; web: boolean; };
}


export interface QueryDraft {
  /**
   * Schema constraints this type cannot express: minItems=1, maxItems=32
   */
  queries: Array<QueryDraftQueriesItem>;
}


export interface ClarificationQuestionQuestionsItem {
  id: "q1";
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=1000
   */
  text: string;
}


export interface ClarificationQuestion {
  /**
   * Schema constraints this type cannot express: minItems=1, maxItems=1
   */
  questions: Array<ClarificationQuestionQuestionsItem>;
}


export type Grounding = GroundingProfile | CorpusManifest | GroundingSession | ClarifiedIntent | QueryPlan | EvidenceCandidate | WebRetrievalRun | EvidenceConflict | GroundedClaim | GroundedAnswer | GroundingIssue | GroundingSpend | GroundingTrace;
