/** Clarification is a declared loop of typed human waits, with a resolved-answer guard. */
import {defineMasWorkflow,graphInvocation,loopInvocation,switchInvocation,interactionInvocation,taskInvocation,masMessage,type MasWorkflow} from '@tangleai/mas';
import {gmplSchemaOf} from '../schema.ts';
import {stageAgent,stageArtifact,pureTask,inputSchema,resultSchema,objectSchema,type PatternBuildContext} from './shared.ts';
export async function buildClarification(maxTurns:number,context:PatternBuildContext){
  const state=gmplSchemaOf('gmplClarificationState'),response=gmplSchemaOf('gmplHumanResponse'),prompt=gmplSchemaOf('gmplHumanPrompt');
  const question=stageArtifact('clarification-question',context),resolve=stageArtifact('clarification-resolve',context),answer=stageArtifact('analysis-merge',context);
  const common={limits:context.limits,registryRevision:null,configRegistryRevision:null,profile:context.profile};
  const waits:MasWorkflow[]=[];
  for(const n of [1,2,3] as const){
    const typed=gmplSchemaOf(`gmplHumanResponse${n}`);
    waits.push(await defineMasWorkflow({...common,workflowId:`gmpl-human-${n}`,title:'Typed human response',description:'Closed answers for the declared question count.',input:objectSchema({state}),output:objectSchema({response}),entry:[{port:'state',to:{node:'prompt',port:'state'}}],exit:[{port:'response',from:{node:'response',port:'response'}}],
      nodes:[pureTask('prompt','gmpl-human-prompt',{state},{prompt}),interactionInvocation({id:'human',input:{prompt},output:{response:typed},prompt,response:typed,expiry:{afterMs:86400000}}),pureTask('response','gmpl-human-response',{response:typed},{response})],messages:[masMessage(['prompt','prompt'],['human','prompt']),masMessage(['human','response'],['response','response'])]}));
  }
  const ask=await defineMasWorkflow({...common,workflowId:'gmpl-clarification-ask',title:'Clarification turn',description:'Question, typed host response, evidence projection and intent resolution.',input:objectSchema({state}),output:objectSchema({state}),entry:[{port:'state',to:{node:'prepare-question',port:'state'}},{port:'state',to:{node:'check-question',port:'state'}}],exit:[{port:'state',from:{node:'resolve-intent',port:'state'}}],nodes:[
    pureTask('prepare-question','gmpl-question-prepare',{state},{variables:question.variableSchema}),await stageAgent('question','clarification-question',context),pureTask('check-question','gmpl-question-check',{state,out:question.outputSchema},{state}),
    switchInvocation({id:'question-count',input:{state},output:{answers:response},mode:'one-of',default:'one',branches:waits.map((w,i)=>({id:['one','two','three'][i],when:{$eq:['$.state.questionCount',i+1]},nodes:[`wait-${i+1}`],result:{node:`wait-${i+1}`,port:'response'}}))}),
    ...waits.map((w,i)=>graphInvocation({id:`wait-${i+1}`,subgraph:w.workflowId,input:{state},output:{response}})),
    pureTask('human-evidence','gmpl-human-evidence',{state,response},{state}),pureTask('prepare-resolution','gmpl-resolve-prepare',{state},{variables:resolve.variableSchema}),await stageAgent('resolve','clarification-resolve',context),pureTask('resolve-intent','gmpl-intent-resolve',{state,out:resolve.outputSchema},{state}),
  ],messages:[masMessage(['prepare-question','variables'],['question','variables']),masMessage(['question','out'],['check-question','out']),masMessage(['check-question','state'],['question-count','state']),masMessage(['check-question','state'],['human-evidence','state']),...waits.map((_,i)=>masMessage(['question-count','state'],[`wait-${i+1}`,'state'])),masMessage(['question-count','answers'],['human-evidence','response']),masMessage(['human-evidence','state'],['prepare-resolution','state']),masMessage(['human-evidence','state'],['resolve-intent','state']),masMessage(['prepare-resolution','variables'],['resolve','variables']),masMessage(['resolve','out'],['resolve-intent','out'])]});
  const turn=await defineMasWorkflow({...common,workflowId:'gmpl-clarification-turn',title:'Guarded clarification turn',description:'Resolved intent skips human questions.',input:objectSchema({state}),output:objectSchema({state}),entry:[{port:'state',to:{node:'intent-route',port:'state'}}],exit:[{port:'state',from:{node:'intent-route',port:'next'}}],nodes:[switchInvocation({id:'intent-route',input:{state},output:{next:state},mode:'one-of',default:'ask',branches:[{id:'resolved',when:{$eq:['$.state.done',true]},nodes:['retain'],result:{node:'retain',port:'next'}},{id:'ask',when:{$eq:['$.state.done',false]},nodes:['ask'],result:{node:'ask',port:'state'}}]}),pureTask('retain','gmpl-clarification-retain',{state},{next:state}),graphInvocation({id:'ask',subgraph:ask.workflowId,input:{state},output:{state}})],messages:[masMessage(['intent-route','state'],['retain','state']),masMessage(['intent-route','state'],['ask','state'])]});
  const fragment=await defineMasWorkflow({...common,workflowId:'gmpl-clarification',title:'Bounded clarification',description:'Inspect intent, pause durably only when needed, answer only when resolved.',input:objectSchema({input:inputSchema}),output:objectSchema({result:resultSchema}),entry:[{port:'input',to:{node:'initialize',port:'input'}}],exit:[{port:'result',from:{node:'answer-route',port:'result'}}],nodes:[
    taskInvocation({id:'initialize',handler:'gmpl-clarification-initialize',input:{input:inputSchema},output:{state},statePull:[{member:'/policy',as:'policy'}]}),pureTask('prepare-inspection','gmpl-intent-prepare',{state},{variables:resolve.variableSchema}),await stageAgent('inspect','clarification-resolve',context),pureTask('inspect-intent','gmpl-intent-inspect',{state,out:resolve.outputSchema},{state}),
    loopInvocation({id:'turns',body:turn.workflowId,input:{state},output:{next:state},init:[{port:'state',to:'/state'}],feedback:[{from:'/state',to:'/state'}],result:[{port:'next',from:'/state'}],maxIterations:maxTurns,termination:{$eq:['$.output.state.done',true]}}),
    switchInvocation({id:'answer-route',input:{state},output:{result:resultSchema},mode:'one-of',default:'unresolved',branches:[{id:'answer',when:{$eq:['$.state.resolved',true]},nodes:['prepare-answer','answer','finish-answer'],result:{node:'finish-answer',port:'result'}},{id:'unresolved',when:{$eq:['$.state.resolved',false]},nodes:['needs-information'],result:{node:'needs-information',port:'result'}}]}),
    pureTask('prepare-answer','gmpl-clarification-answer',{state},{variables:answer.variableSchema}),await stageAgent('answer','analysis-merge',context),pureTask('finish-answer','gmpl-clarification-finalize',{state,out:answer.outputSchema},{result:resultSchema}),pureTask('needs-information','gmpl-clarification-unresolved',{state},{result:resultSchema}),
  ],messages:[masMessage(['initialize','state'],['prepare-inspection','state']),masMessage(['initialize','state'],['inspect-intent','state']),masMessage(['prepare-inspection','variables'],['inspect','variables']),masMessage(['inspect','out'],['inspect-intent','out']),masMessage(['inspect-intent','state'],['turns','state']),masMessage(['turns','next'],['answer-route','state']),masMessage(['answer-route','state'],['prepare-answer','state']),masMessage(['answer-route','state'],['finish-answer','state']),masMessage(['answer-route','state'],['needs-information','state']),masMessage(['prepare-answer','variables'],['answer','variables']),masMessage(['answer','out'],['finish-answer','out'])]});
  return {fragment,subgraphs:[...waits,ask,turn]};
}
