// Generated by @jarenjs/emit from packages/forecast/schemas/outcome-adapter.schema.json.
// Do not edit: regenerate instead.

/**
 * Schema constraints this type cannot express: minLength=1, pattern="\\S"
 */
export type InputAdapterOneOf1OptionsItem = string;

export interface InputAdapterOneOf1 {
  id: "choice/v1";
  /**
   * Schema constraints this type cannot express: minLength=1, pattern="\\S"
   */
  version: string;
  /**
   * Schema constraints this type cannot express: minItems=2, maxItems=1000, uniqueItems=true
   */
  options: Array<InputAdapterOneOf1OptionsItem>;
}


export interface InputAdapterOneOf2 {
  id: "numeric/v1";
  /**
   * Schema constraints this type cannot express: minLength=1, pattern="\\S"
   */
  version: string;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  tolerance: number;
  /**
   * Schema constraints this type cannot express: minItems=2, maxItems=2
   */
  range: Array<number>;
  /**
   * Schema constraints this type cannot express: minLength=1, pattern="\\S"
   */
  unit?: string;
}


export interface Input {
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  questionId: string;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  checkpointId: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1
   */
  ordinal: number;
  /**
   * Schema constraints this type cannot express: pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$"
   */
  cutoffAt: string;
  adapter: InputAdapterOneOf1 | InputAdapterOneOf2;
  /**
   * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
   */
  usedHarnessDigest: string;
  /**
   * Schema constraints this type cannot express: maxProperties=64, patternProperties=["^[a-f0-9]{64}$"]
   */
  predictions: { [key: string]: string | number; };
}


/**
 * Schema constraints this type cannot express: minLength=1, pattern="\\S"
 */
export type OutputAdapterOneOf1OptionsItem = string;

export interface OutputAdapterOneOf1 {
  id: "choice/v1";
  /**
   * Schema constraints this type cannot express: minLength=1, pattern="\\S"
   */
  version: string;
  /**
   * Schema constraints this type cannot express: minItems=2, maxItems=1000, uniqueItems=true
   */
  options: Array<OutputAdapterOneOf1OptionsItem>;
}


export interface OutputAdapterOneOf2 {
  id: "numeric/v1";
  /**
   * Schema constraints this type cannot express: minLength=1, pattern="\\S"
   */
  version: string;
  /**
   * Schema constraints this type cannot express: exclusiveMinimum=0
   */
  tolerance: number;
  /**
   * Schema constraints this type cannot express: minItems=2, maxItems=2
   */
  range: Array<number>;
  /**
   * Schema constraints this type cannot express: minLength=1, pattern="\\S"
   */
  unit?: string;
}


export interface Output {
  answer: string | number | null;
  status: "predicted" | "not-run-under-harness";
  adapter: OutputAdapterOneOf1 | OutputAdapterOneOf2;
}


export interface Resolution {
  outcome: string | number;
}


export interface Artifact {
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=4096, pattern="\\S"
   */
  factorTracking: string;
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=4096, pattern="\\S"
   */
  evidenceHandling: string;
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=4096, pattern="\\S"
   */
  uncertaintyHandling: string;
}


export type OutcomeAdapter = unknown;
