/**
 * Generate `apps/desktop/src/assets.gen.ts` — the UI files as string
 * constants, so `bun build --compile` produces ONE self-contained
 * binary with the frontend inside. Dev servers never need this file
 * (static serving prefers disk); it is gitignored and produced by
 * `npm run desktop:compile`.
 *
 * Run: bun scripts/embed-assets.ts   (or node scripts/embed-assets.ts)
 */

import { readResearchReport } from '../apps/desktop/src/research-report.ts';
import { researchContext, validateResearchReport } from '../benchmark/lib/research.ts';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const publicDir = join(here, '..', 'apps', 'desktop', 'public');
const target = join(here, '..', 'apps', 'desktop', 'src', 'assets.gen.ts');

const entries = await readdir(publicDir);
const assets: Record<string, string> = {};
for (const name of entries.sort()) {
  assets[name] = await readFile(join(publicDir, name), 'utf8');
}

const bytes = await readFile(join(here, '..', 'benchmark/results/research.json'), 'utf8');
const researchDocument = JSON.parse(bytes), context = await researchContext(join(here, '..'));
if (!await validateResearchReport(researchDocument, context)) throw new Error('The research report did not independently reproduce for this binary.');
const research = { bytes, sourceFiles: context.source.files, expectedReportId: researchDocument.reportId };
const verified = await readResearchReport(async () => research);
if (!verified.ok) throw new Error(JSON.stringify(verified));
assets['research-report.json'] = research.bytes;
assets['research-source.json'] = JSON.stringify({ sourceFiles: research.sourceFiles, expectedReportId: research.expectedReportId });

const body = `// GENERATED by scripts/embed-assets.ts — do not edit, do not commit.
export const ASSETS: Record<string, string> = ${JSON.stringify(assets)};
`;
await writeFile(target, body);
console.log(`embedded ${Object.keys(assets).length} assets (${body.length} chars) → ${target}`);
