/**
 * Generate `apps/desktop/src/assets.gen.ts` — the UI files as string
 * constants, so `bun build --compile` produces ONE self-contained
 * binary with the frontend inside. Dev servers never need this file
 * (static serving prefers disk); it is gitignored and produced by
 * `npm run desktop:compile`.
 *
 * Run: bun scripts/embed-assets.ts   (or node scripts/embed-assets.ts)
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const publicDir = join(here, '..', 'apps', 'desktop', 'public');
const target = join(here, '..', 'apps', 'desktop', 'src', 'assets.gen.ts');

const entries = await readdir(publicDir);
const assets: Record<string, string> = {};
for (const name of entries.sort()) {
  assets[name] = await readFile(join(publicDir, name), 'utf8');
}

const body = `// GENERATED by scripts/embed-assets.ts — do not edit, do not commit.
export const ASSETS: Record<string, string> = ${JSON.stringify(assets)};
`;
await writeFile(target, body);
console.log(`embedded ${Object.keys(assets).length} assets (${body.length} chars) → ${target}`);
