/** Generate/check the public memory policy without any provider call. */
import assert from 'node:assert/strict';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { compileContract } from '@jarenjs/contract';
import { pathToFileURL } from 'node:url';
import { readPolicyDecision } from './lib/policy-default.ts';

const object = (properties: Record<string, unknown>) => ({ type: 'object', additionalProperties: false, required: Object.keys(properties), properties });
const number = { type: 'number' }, string = { type: 'string' }, integer = { type: 'integer', minimum: 0 };
const mechanism = object({ enabled: { type: 'boolean' }, threshold: number });
const provenanceSchema = object({
  reportId: string, registrationId: string, cellId: string, sourceId: string, transitionId: string, challengerId: string,
  ingestTier: { const: 'live' }, retrievalTier: { const: 'live' }, embeddingTier: { const: 'keyless' },
  qualifiesAsDefault: { type: 'boolean' }, statement: string,
  power: object({ pairedSd: number, standardError: number, minimumDetectableEffect: number, tiedPairs: integer, actingSetSize: integer }),
  interval: object({ low: number, high: number }),
  clauses: { type: 'array', items: object({ clause: string, passed: { type: 'boolean' }, detail: string }) },
});
export const POLICY_CONTRACT = {
  $contract: '0.1', id: 'tangle-memory-policy', version: '1',
  operations: {
    'policy.provenance': { kind: 'read', input: object({}), output: provenanceSchema },
    'policy.read': { kind: 'read', input: object({}), output: object({
      novelty: mechanism,
      contradiction: object({ enabled: { type: 'boolean' }, threshold: number, maxPairs: integer }),
      crystallization: mechanism,
      retrieval: object({ k: integer, minScore: number }),
      embedding: object({ model: string, dims: integer, tier: { type: 'string', enum: ['keyless'] } }),
    }) },
  },
};
export async function generatedPolicy(reportPath: string): Promise<string> {
  const { artifact } = await readPolicyDecision(reportPath);
  const contract = compileContract(POLICY_CONTRACT);
  assert.ok(contract.operations['policy.read'].output.validate(artifact.policy).valid, 'Selected policy does not satisfy its public contract');
  assert.ok(contract.operations['policy.provenance'].output.validate(artifact.provenance).valid, 'Policy provenance does not satisfy its public contract');
  const revision = await contract.revision();
  return `// Generated by scripts/policy-default.ts from the registered confirmation. Do not edit.\nimport type { MemoryPolicyValues } from './policy.ts';\nimport { deepFreeze } from '@jarenjs/core/object';\n\nexport const DEFAULT_MEMORY_POLICY: Readonly<MemoryPolicyValues> = deepFreeze(${JSON.stringify(artifact.policy, null, 2)});\n\nexport const POLICY_PROVENANCE = deepFreeze(${JSON.stringify(artifact.provenance, null, 2)} as const);\n\nexport const MEASURED_MEMORY_POLICIES: Readonly<Record<string, MemoryPolicyValues & { label: string }>> = deepFreeze(${JSON.stringify(artifact.alternatives, null, 2)});\n\nexport const SHIPPED_LEGACY_CELL_ID = ${JSON.stringify(artifact.shippedLegacyCellId)};\nexport const POLICY_CONTRACT_REVISION = ${JSON.stringify(revision)};\n`;
}
async function main() {
  const args = process.argv.slice(2);
  const reportIndex = args.indexOf('--report');
  const report = reportIndex < 0 ? 'benchmark/results/locomo-policy.json' : args[reportIndex + 1];
  assert.ok(report, '--report requires a path');
  const output = await generatedPolicy(report);
  const { artifact } = await readPolicyDecision(report);
  const registryPath = 'config/profiles.json';
  const registry = JSON.parse(await readFile(registryPath, 'utf8'));
  const previousComponent = registry.components.find((c: { kind: string }) => c.kind === 'policy');
  const component = { id: 'memory-policies-selected', kind: 'policy', package: '@tangleai/memory', export: 'DEFAULT_MEMORY_POLICY',
    revision: artifact.provenance.reportId, description: `Measured default cell ${artifact.provenance.cellId}; effective values and live/lexical provenance are owned by @tangleai/memory/policy.` };
  const offline = registry.candidates.find((c: { kind: string, provider: string }) => c.kind === 'embedding' && c.provider === 'builtin');
  const newOfflineId = `builtin-hash-${artifact.policy.embedding.dims}`;
  const expectedRegistry = structuredClone(registry);
  expectedRegistry.components = registry.components.map((c: { id: string }) => c.id === previousComponent.id ? component : c);
  expectedRegistry.candidates = registry.candidates.map((c: { id: string }) => c.id === offline.id
    ? { ...c, id: newOfflineId, model: artifact.policy.embedding.model, dims: artifact.policy.embedding.dims,
      limitations: 'Lexical hash width selected by registered evidence recall; no semantic answer-quality claim.' } : c);
  for (const profile of expectedRegistry.profiles) {
    if (profile.policyComponent === previousComponent.id) profile.policyComponent = component.id;
    if (profile.embedding === offline.id) profile.embedding = newOfflineId;
  }
  const target = 'packages/memory/src/policy.gen.ts';
  const schema = `${JSON.stringify(POLICY_CONTRACT, null, 2)}\n`;
  const valueSchema = `${JSON.stringify({ $schema: 'http://json-schema.org/draft-07/schema#', $id: 'https://tangleai.dev/schemas/memory-policy-values', title: 'MemoryPolicyValues', ...POLICY_CONTRACT.operations['policy.read'].output }, null, 2)}\n`;
  if (args.includes('--check')) {
    assert.deepEqual(registry, expectedRegistry, 'Config registry drifted from its owned policy and offline width');
    assert.equal(await readFile(target, 'utf8'), output, 'Runtime policy drifted from the confirmed report');
    assert.equal(await readFile('packages/memory/schemas/policy.contract.json', 'utf8'), schema, 'Public policy contract drifted');
    assert.equal(await readFile('packages/memory/schemas/policy.schema.json', 'utf8'), valueSchema, 'Memory value schema drifted');
    const { verifyRuntimePolicy } = await import('./lib/policy-runtime.ts');
    await verifyRuntimePolicy(artifact.policy);
    console.log('Policy defaults, provenance, alternatives and public contract match the confirmed report.');
  } else {
    await mkdir('packages/memory/schemas', { recursive: true });
    await writeFile(target, output);
    await writeFile(registryPath, `${JSON.stringify(expectedRegistry, null, 2)}\n`);
    await writeFile('packages/memory/schemas/policy.contract.json', schema);
    await writeFile('packages/memory/schemas/policy.schema.json', valueSchema);
    console.log(`Generated ${target}`);
  }
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await main();
