// Generated by @jarenjs/emit from packages/memory/schemas/policy.schema.json.
// Do not edit: regenerate instead.

export interface PolicyContradiction {
  enabled: boolean;
  threshold: number;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  maxPairs: number;
}


export interface PolicyRetrieval {
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  k: number;
  minScore: number;
}


export interface PolicyEmbedding {
  model: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=0
   */
  dims: number;
  tier: "keyless";
}


export interface Policy {
  novelty: { enabled: boolean; threshold: number; };
  contradiction: PolicyContradiction;
  crystallization: { enabled: boolean; threshold: number; };
  retrieval: PolicyRetrieval;
  embedding: PolicyEmbedding;
}


