// Generated by @jarenjs/emit from packages/evolve/schemas/evolve.schema.json.
// Do not edit: regenerate instead.

/**
 * Schema constraints this type cannot express: pattern="^[a-f0-9]{64}$"
 */
export type Sha256 = string;

/**
 * Schema constraints this type cannot express: pattern="^[a-f0-9]{40}$"
 */
export type Revision40 = string;

/**
 * Schema constraints this type cannot express: minLength=1, maxLength=512
 */
export type Id = string;

/**
 * Schema constraints this type cannot express: type="integer", minimum=0
 */
export type Count = number;

/**
 * Schema constraints this type cannot express: type="integer", minimum=1
 */
export type Positive = number;

/**
 * Schema constraints this type cannot express: minLength=1, maxLength=4096
 */
export type Text = string;

/**
 * Schema constraints this type cannot express: minLength=1, maxLength=512, pattern="^[A-Za-z0-9._][A-Za-z0-9._*\/-]*$"
 */
export type RepoPath = string;

export type EvolveCode = "TEVO1001" | "TEVO1002" | "TEVO1003" | "TEVO1004" | "TEVO1005" | "TEVO1006" | "TEVO1007" | "TEVO1008" | "TEVO1009" | "TEVO1010" | "TEVO1011";

export type Decision = "kept" | "abandoned" | "refused" | "uncertain";

export type DecisionReason = "improved" | "equal" | "regression" | "red" | "ambiguous" | "over-budget" | "unverifiable" | "goalpost" | "escape" | "command" | "uncertain-effect";

export type Status = "proposed" | "isolated" | "applied" | "gated" | "measured" | "decided" | "recorded" | "abandoned" | "refused" | "uncertain";

export type Direction = "lower" | "higher";

export type Origin = "hand-authored" | "checked-skill" | "model";

export interface EvolveIssueCause {
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  code: string;
  docPath: string;
  message: string;
}


export interface EvolveIssue {
  code: EvolveCode;
  path: string;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  detail: string;
  cause?: EvolveIssueCause;
}


export interface EvolveBudgets {
  patchBytes: Positive;
  patchFiles: Positive;
  attemptsPerLeg: 1;
  calls: Count;
  tokens: Count;
  legMs: Positive;
  experimentMs: Positive;
  stdoutBytes: Positive;
  stderrBytes: Positive;
  workspaceBytes: Positive;
  samples: Positive;
}


export interface EvolvePrincipal {
  id: Id;
  authorityId: Id;
  propose: boolean;
  execute: boolean;
  approve: boolean;
}


/**
 * Schema constraints this type cannot express: maxLength=512
 */
export type CommandArgsItem = string;

export interface Command {
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=128
   */
  command: string;
  /**
   * Schema constraints this type cannot express: maxItems=64
   */
  args: Array<CommandArgsItem>;
}


export interface MetricSpec {
  name: Text;
  direction: Direction;
  schema: { [key: string]: unknown; };
}


/**
 * Schema constraints this type cannot express: maxLength=512
 */
export type EvolveRepositoryPolicyInstrumentArgsItem = string;

export interface EvolveRepositoryPolicyInstrument {
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=128
   */
  command: string;
  /**
   * Schema constraints this type cannot express: maxItems=64
   */
  args: Array<EvolveRepositoryPolicyInstrumentArgsItem>;
  metric: MetricSpec;
}


/**
 * Schema constraints this type cannot express: minLength=1, maxLength=128
 */
export type EvolveRepositoryAllowCommandsItem = string;

export interface EvolveRepository {
  schemaVersion: 1;
  kind: "repository";
  id: Sha256;
  repositoryId: Id;
  vcs: "git";
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  protectedRefs: Array<Text>;
  policy: { immutablePaths: Array<RepoPath>; generated: Array<RepoPath>; gate: Command; instrument: EvolveRepositoryPolicyInstrument; thresholdsPath: RepoPath; };
  allow: { commands: Array<EvolveRepositoryAllowCommandsItem>; };
  budgets: EvolveBudgets;
}


export interface EvolveBase {
  schemaVersion: 1;
  kind: "base";
  id: Sha256;
  repositoryId: Id;
  revision: Revision40;
  clean: true;
  operatorBranch: Text;
  checkedOut: Array<RepoPath>;
}


export interface EvolveStrategy {
  schemaVersion: 1;
  kind: "strategy";
  id: Sha256;
  strategyId: Id;
  skillId: Id;
  memoryId: Id;
  origin: Origin;
  evidence: Array<Id>;
  revision: Id;
}


export interface EvolvePatchOperationsItem {
  op: "add" | "replace" | "remove";
  /**
   * Schema constraints this type cannot express: pattern="^/files/"
   */
  path: string;
  value?: unknown;
}


export interface EvolvePatch {
  schemaVersion: 1;
  kind: "patch";
  id: Sha256;
  patchId: Id;
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  operations: Array<EvolvePatchOperationsItem>;
  files: Positive;
  bytes: Count;
}


export interface EvolveProposal {
  schemaVersion: 1;
  kind: "proposal";
  id: Sha256;
  proposalId: Id;
  experimentId: Id;
  strategyId: Id;
  patchId: Id;
  rationale: Text;
  evidence: Array<Id>;
  origin: Origin;
  configuration: { kind: "scripted"; revision: Id; } | { kind: "model"; identityId: Id; };
}


export interface EvolveGateResult {
  schemaVersion: 1;
  kind: "gate-result";
  id: Sha256;
  experimentId: Id;
  leg: "gate" | "gate-rerun";
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  exitCode: number | null;
  signal: string | null;
  stdoutBytes: Count;
  stderrBytes: Count;
  truncated: { stdout: boolean; stderr: boolean; };
  effectRecordId: Id;
}


export interface SampleSet {
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  samples: Array<number>;
  median: number;
}


export interface EvolveMeasurement {
  schemaVersion: 1;
  kind: "measurement";
  id: Sha256;
  experimentId: Id;
  metric: Text;
  direction: Direction;
  base: SampleSet;
  candidate: SampleSet;
  truth: number;
  delta: number;
  effectRecordIds: Array<Id>;
}


export interface EvolveDecision {
  schemaVersion: 1;
  kind: "decision";
  id: Sha256;
  experimentId: Id;
  decision: Decision;
  reason: DecisionReason;
  code: EvolveCode | null;
  evidenceIds: Array<Id>;
  budgets: EvolveBudgets;
}


export interface EvolveReviewBundle {
  schemaVersion: 1;
  kind: "review-bundle";
  id: Sha256;
  experimentId: Id;
  branch: Text;
  headRevision: Revision40;
  diffDigest: Sha256;
  diffBytes: Count;
  gateResultIds: Array<Id>;
  measurementId: Id;
  decisionId: Id;
  runIdentityId: Id;
  effectRecordIds: Array<Id>;
}


export interface EvolveExperiment {
  schemaVersion: 1;
  kind: "experiment";
  id: Sha256;
  experimentId: Id;
  repositoryId: Id;
  baseRevision: Revision40;
  strategyId: Id;
  proposalId: Id;
  status: Status;
  runIdentityId: Id;
  revision: Count;
  history: Array<{ from: Status; to: Status; recordId: Id; }>;
}


export type EvolveRecord = EvolveRepository | EvolveBase | EvolveStrategy | EvolvePatch | EvolveProposal | EvolveGateResult | EvolveMeasurement | EvolveDecision | EvolveReviewBundle | EvolveExperiment;

export type Evolve = EvolveRecord;

